package cn.xuexizhitu.service;
import cn.xuexizhitu.common.*;
import static cn.xuexizhitu.common.BusinessData.*;
import cn.xuexizhitu.repository.*;
import cn.xuexizhitu.security.CurrentUser;
import cn.xuexizhitu.validation.BusinessInput;
import com.fasterxml.jackson.databind.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import java.time.*;
import java.util.*;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class AdminService {
    private final JdbcTemplate jdbc;private final LearningRepository learning;private final LearningService courses;private final ExamService exams;private final PrivateFileStore files;private final AuditRepository audit;private final AssessmentRepository assessments;private final PracticeRepository practice;private final BusinessInput input;private final ObjectMapper mapper;
    private Object page(List<?> items,int page,int size,long total){return obj("items",items,"page",page,"size",size,"total",total);}
    private Map<String,Object> one(String sql,Object...args){return jdbc.queryForList(sql,args).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
    @Transactional public Object course(String id,JsonNode w,String cycle){input.validate("CourseAdminWrite",w);learning.requireCycle(cycle);if(id==null){id=uuid();jdbc.update("INSERT INTO course(id,code,name,course_type,active) VALUES(?,?,?,?,?)",id,str(w,"code"),str(w,"name"),str(w,"courseType"),w.path("active").asBoolean());jdbc.update("INSERT INTO cycle_course(cycle_id,course_id) VALUES(?,?)",cycle,id);}else{one("SELECT * FROM course WHERE id=? FOR UPDATE",id);jdbc.update("UPDATE course SET code=?,name=?,course_type=?,active=? WHERE id=?",str(w,"code"),str(w,"name"),str(w,"courseType"),w.path("active").asBoolean(),id);}audit.add("COURSE_UPDATED","COURSE",id,null,obj("code",str(w,"code")));return courseDto(id,cycle);}
    public Object courseDto(String id,String cycle){var c=one("SELECT * FROM course WHERE id=?",id);String release=jdbc.queryForList("SELECT id FROM content_release WHERE course_id=? AND state='PUBLISHED' ORDER BY version_no DESC LIMIT 1",String.class,id).stream().findFirst().orElse(null);return obj("id",id,"code",c.get("code"),"name",c.get("name"),"courseType",c.get("course_type"),"active",c.get("active"),"releaseId",release,"progress",learning.progress(CurrentUser.idOrThrow(),release),"enrollment",learning.enrollment(CurrentUser.idOrThrow(),id,cycle),"capabilities",obj("catalog",release!=null,"knowledge",release!=null&&jdbc.queryForObject("SELECT COUNT(*) FROM module_revision WHERE release_id=?",Integer.class,release)>0,"practice",release!=null&&practice.hasPractice(release),"exams",c.get("course_type").equals("THEORY"),"manual",c.get("course_type").equals("PRACTICE")));}
    private LocalTime time(String value){try{return LocalTime.parse(value);}catch(java.time.DateTimeException e){throw new BusinessException(ErrorCode.INVALID_PARAMETER,"考试时段格式无效");}}
    @Transactional public Object cycle(String id,JsonNode w){input.validate("CycleWrite",w);require(!LocalDate.parse(str(w,"endDate")).isBefore(LocalDate.parse(str(w,"startDate"))),ErrorCode.INVALID_RELATION,"周期结束早于开始");Set<String> ids=new HashSet<>();for(JsonNode c:w.path("courses")){require(ids.add(str(c,"courseId")),ErrorCode.INVALID_RELATION,"周期课程重复");one("SELECT id FROM course WHERE id=?",str(c,"courseId"));String day=str(c,"examDate"),start=str(c,"startsAt"),end=str(c,"endsAt");require((start==null)==(end==null),ErrorCode.INVALID_RELATION,"考试时段需成对填写");if(start!=null)require(day!=null&&time(start).isBefore(time(end)),ErrorCode.INVALID_RELATION,"考试时段无效");}
        if(id==null){id=uuid();jdbc.update("INSERT INTO exam_cycle(id,name,start_date,end_date) VALUES(?,?,?,?)",id,str(w,"name"),str(w,"startDate"),str(w,"endDate"));}else{one("SELECT id FROM exam_cycle WHERE id=? FOR UPDATE",id);jdbc.update("UPDATE exam_cycle SET name=?,start_date=?,end_date=? WHERE id=?",str(w,"name"),str(w,"startDate"),str(w,"endDate"),id);for(String old:jdbc.queryForList("SELECT course_id FROM cycle_course WHERE cycle_id=?",String.class,id))if(!ids.contains(old)){require(jdbc.queryForObject("SELECT COUNT(*) FROM enrollment WHERE course_id=? AND cycle_id=?",Integer.class,old,id)==0,ErrorCode.INVALID_RELATION,"已有报考的周期科目不能移除");jdbc.update("DELETE FROM cycle_course WHERE cycle_id=? AND course_id=?",id,old);}}
        for(JsonNode c:w.path("courses"))jdbc.update("INSERT INTO cycle_course(cycle_id,course_id,exam_date,starts_at,ends_at) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE exam_date=VALUES(exam_date),starts_at=VALUES(starts_at),ends_at=VALUES(ends_at)",id,str(c,"courseId"),str(c,"examDate"),str(c,"startsAt"),str(c,"endsAt"));audit.add("CYCLE_UPDATED","EXAM_CYCLE",id,null,obj("courseCount",ids.size()));return learning.cycle(id);}
    public Object files(String purpose,int page,int size){require(purpose==null||Set.of("PAPER","MANUAL").contains(purpose),ErrorCode.INVALID_PARAMETER,"用途无效");String where=" WHERE purpose IN ('PAPER','MANUAL')"+(purpose==null?"":" AND purpose=?");List<Object> args=new ArrayList<>();if(purpose!=null)args.add(purpose);long total=jdbc.queryForObject("SELECT COUNT(*) FROM stored_file"+where,Long.class,args.toArray());args.add(size);args.add((page-1L)*size);return page(jdbc.queryForList("SELECT id FROM stored_file"+where+" ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?",String.class,args.toArray()).stream().map(files::metadata).toList(),page,size,total);}
    @Transactional public Object upload(MultipartFile file,String purpose,boolean containsAnswers){require(Set.of("PAPER","MANUAL").contains(purpose),ErrorCode.INVALID_PARAMETER,"用途无效");String id=files.upload(file,purpose,null,containsAnswers);audit.add("CONTENT_FILE_UPLOADED","STORED_FILE",id,null,obj("purpose",purpose,"containsAnswers",containsAnswers));return files.metadata(id);}
    @Transactional public Object paper(String course,String id,JsonNode w){input.validate("PaperWrite",w);learning.course(course);String month=str(w,"paperMonth");require(!month.startsWith("0000"),ErrorCode.INVALID_RELATION,"试卷月份无效");for(String field:List.of("questionFileId","answerFileId")){String file=str(w,field);if(file!=null){var f=files.row(file);require(f.get("purpose").equals("PAPER")&&f.get("state").equals("ACTIVE"),ErrorCode.INVALID_RELATION,"试卷文件用途或状态无效");}}
        require(jdbc.queryForObject("SELECT COUNT(*) FROM paper WHERE course_id=? AND paper_month=? AND id<>?",Integer.class,course,month+"-01",id==null?"":id)==0,ErrorCode.CONFLICT,"课程与月份已有试卷");if(id==null){id=uuid();jdbc.update("INSERT INTO paper(id,course_id,paper_month,source_course_code,question_file_id,answer_file_id,question_pages,answer_pages,note) VALUES(?,?,?,?,?,?,?,?,?)",id,course,month+"-01",value(w,"sourceCourseCode"),str(w,"questionFileId"),str(w,"answerFileId"),value(w,"questionPages"),value(w,"answerPages"),str(w,"note"));}else{exams.paper(course,id);jdbc.update("UPDATE paper SET paper_month=?,source_course_code=?,question_file_id=?,answer_file_id=?,question_pages=?,answer_pages=?,note=? WHERE id=? AND course_id=?",month+"-01",value(w,"sourceCourseCode"),str(w,"questionFileId"),str(w,"answerFileId"),value(w,"questionPages"),value(w,"answerPages"),str(w,"note"),id,course);}audit.add("PAPER_UPDATED","PAPER",id,null,obj("courseId",course,"paperMonth",month));return exams.paper(course,id);}
    private Map<String,Object> pass(Map<String,Object> r){return obj("id",r.get("id"),"kind",r.get("kind"),"chapterId",r.get("chapter_id"),"releaseId",r.get("release_id"),"source",r.get("source"),"grantedAt",instant(r,"granted_at"),"invalidatedAt",instant(r,"invalidated_at"),"invalidatedBy",r.get("invalidated_by"),"invalidationReason",r.get("invalidation_reason"));}
    public Object passes(String course,String kind,String chapter,boolean valid,int page,int size){learning.course(course);require(kind==null||Set.of("CHAPTER","MOCK").contains(kind),ErrorCode.INVALID_PARAMETER,"通过类型无效");String sql=" FROM assessment_pass WHERE user_id=? AND course_id=?";List<Object> args=new ArrayList<>(List.of(CurrentUser.idOrThrow(),course));if(kind!=null){sql+=" AND kind=?";args.add(kind);}if(chapter!=null){sql+=" AND chapter_id=?";args.add(chapter);}if(valid)sql+=" AND invalidated_at IS NULL";long total=jdbc.queryForObject("SELECT COUNT(*)"+sql,Long.class,args.toArray());args.add(size);args.add((page-1L)*size);return page(jdbc.queryForList("SELECT *"+sql+" ORDER BY granted_at DESC,id DESC LIMIT ? OFFSET ?",args.toArray()).stream().map(this::pass).toList(),page,size,total);}
    @Transactional public Object invalidate(String id,JsonNode w){input.validate("InvalidatePass",w);var owner=one("SELECT user_id FROM assessment_pass WHERE id=?",id);learning.lockUser((String)owner.get("user_id"));var p=one("SELECT * FROM assessment_pass WHERE id=? FOR UPDATE",id);require(p.get("invalidated_at")==null,ErrorCode.CONFLICT,"通过记录已作废");require(!str(w,"reason").isBlank(),ErrorCode.INVALID_PARAMETER,"须填写作废原因");jdbc.update("UPDATE assessment_pass SET invalidated_at=UTC_TIMESTAMP(6),invalidated_by=?,invalidation_reason=? WHERE id=?",CurrentUser.idOrThrow(),str(w,"reason"),id);audit.add("PASS_INVALIDATED","ASSESSMENT_PASS",id,str(w,"reason"),obj("courseId",p.get("course_id"),"ownerId",p.get("user_id")));String course=(String)p.get("course_id");var unlocks=jdbc.queryForList("SELECT cycle_id FROM enrollment WHERE user_id=? AND course_id=? ORDER BY cycle_id",String.class,p.get("user_id"),course).stream().map(c->assessments.unlock((String)p.get("user_id"),course,c,learning.course(course).releaseId())).toList();return obj("pass",pass(one("SELECT * FROM assessment_pass WHERE id=?",id)),"affectedUnlocks",unlocks,"evaluatedAt",Instant.now());}
    private Map<String,Object> alert(Map<String,Object> r){String code=(String)r.get("alert_code");if(code.equals("ASSESSMENT_BANK_INSUFFICIENT"))code="INSUFFICIENT_QUESTIONS";String message;try{message=mapper.readTree(r.get("details").toString()).path("reason").asText("题库需复核");}catch(Exception e){message="题库需复核";}return obj("id",r.get("id"),"courseId",r.get("course_id"),"chapterId",r.get("chapter_id"),"releaseId",r.get("release_id"),"alertCode",code,"message",message,"createdAt",instant(r,"created_at"),"acknowledgedAt",instant(r,"acknowledged_at"));}
    public Object alerts(String course,Boolean acknowledged,int page,int size){String sql=" FROM bank_alert WHERE 1=1";List<Object> args=new ArrayList<>();if(course!=null){sql+=" AND course_id=?";args.add(course);}if(acknowledged!=null)sql+=" AND acknowledged_at IS "+(acknowledged?"NOT NULL":"NULL");long total=jdbc.queryForObject("SELECT COUNT(*)"+sql,Long.class,args.toArray());args.add(size);args.add((page-1L)*size);return page(jdbc.queryForList("SELECT *"+sql+" ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?",args.toArray()).stream().map(this::alert).toList(),page,size,total);}
    @Transactional public Object acknowledge(String id,JsonNode w){input.validate("OverrideConfirm",w);one("SELECT id FROM bank_alert WHERE id=? FOR UPDATE",id);jdbc.update("UPDATE bank_alert SET acknowledged_at=COALESCE(acknowledged_at,UTC_TIMESTAMP(6)),acknowledged_by=COALESCE(acknowledged_by,?) WHERE id=?",CurrentUser.idOrThrow(),id);audit.add("BANK_ALERT_ACKNOWLEDGED","BANK_ALERT",id,null,Map.of());return alert(one("SELECT * FROM bank_alert WHERE id=?",id));}
    public Object audits(String action,String target,int page,int size){String sql=" FROM audit_event WHERE 1=1";List<Object> args=new ArrayList<>();if(action!=null){sql+=" AND action=?";args.add(action);}if(target!=null){sql+=" AND target_id=?";args.add(target);}long total=jdbc.queryForObject("SELECT COUNT(*)"+sql,Long.class,args.toArray());args.add(size);args.add((page-1L)*size);return page(jdbc.queryForList("SELECT *"+sql+" ORDER BY occurred_at DESC,id DESC LIMIT ? OFFSET ?",args.toArray()).stream().map(r->obj("id",r.get("id"),"actorId",r.get("actor_id"),"action",r.get("action"),"targetType",r.get("target_type"),"targetId",r.get("target_id"),"reason",r.get("reason"),"details",r.get("details").toString(),"occurredAt",instant(r,"occurred_at"))).toList(),page,size,total);}
    public static Instant instant(Map<String,Object> r,String field){Object v=r.get(field);return v==null?null:((LocalDateTime)v).toInstant(ZoneOffset.UTC);}
}
