package cn.xuexizhitu.service;
import cn.xuexizhitu.common.*;
import static cn.xuexizhitu.common.BusinessData.*;
import cn.xuexizhitu.repository.*;
import cn.xuexizhitu.validation.BusinessInput;
import cn.xuexizhitu.security.CurrentUser;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
import java.text.Normalizer;
import java.nio.charset.StandardCharsets;

@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class ContentAdminService {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;private final BusinessInput input;private final AuditRepository audit;private final PrivateFileStore files;private final AssessmentRepository assessments;
    private JsonNode parse(Object value){try{return value==null?mapper.nullNode():mapper.readTree(value.toString());}catch(Exception e){throw new IllegalStateException(e);}}
    private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
    private Map<String,Object> raw(String course,String release,boolean lock){return jdbc.queryForList("SELECT * FROM content_release WHERE id=? AND course_id=?"+(lock?" FOR UPDATE":""),release,course).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
    private Map<String,Object> releaseDto(Map<String,Object> r){return obj("id",r.get("id"),"courseId",r.get("course_id"),"versionNo",r.get("version_no"),"state",r.get("state"),"publishedAt",r.get("published_at")==null?null:((LocalDateTime)r.get("published_at")).toInstant(ZoneOffset.UTC),"sourceSha",r.get("source_sha"));}
    public Object releases(String course,int page,int size){require(jdbc.queryForObject("SELECT COUNT(*) FROM course WHERE id=?",Integer.class,course)>0,ErrorCode.NOT_FOUND,"课程不存在");return obj("items",jdbc.queryForList("SELECT * FROM content_release WHERE course_id=? ORDER BY version_no DESC,id LIMIT ? OFFSET ?",course,size,(page-1L)*size).stream().map(this::releaseDto).toList(),"page",page,"size",size,"total",jdbc.queryForObject("SELECT COUNT(*) FROM content_release WHERE course_id=?",Long.class,course));}
    private ObjectNode defaults(String course){ObjectNode result=mapper.createObjectNode();for(String section:List.of("catalog","knowledge","questions","task-templates"))result.set(section,mapper.valueToTree(obj(section.equals("catalog")?"chapters":section.equals("knowledge")?"modules":section.equals("questions")?"questions":"templates",List.of())));result.set("assessment-policy",mapper.valueToTree(obj("id",uuid(),"courseId",course,"releaseId",null,"gateRatio",0.6,"gateFloor",20,"gateCap",100,"chapterMinQuestions",20,"chapterMaxQuestions",40,"chapterLimitMinutes",40,"chapterPassScore",90,"mockQuestionCount",40,"mockLimitMinutes",80,"mockPassScore",80,"weights",List.of())));return result;}
    @Transactional public Object create(String course,JsonNode w){input.validate("ReleaseCreate",w);require(!jdbc.queryForList("SELECT id FROM course WHERE id=? FOR UPDATE",String.class,course).isEmpty(),ErrorCode.NOT_FOUND,"课程不存在");String id=uuid();ObjectNode content=defaults(course);String base=str(w,"basedOnReleaseId");if(base!=null){raw(course,base,false);for(String section:List.of("catalog","knowledge","questions","task-templates","assessment-policy"))content.set(section,mapper.valueToTree(section(course,base,section)));Map<String,String> examples=new HashMap<>();for(JsonNode m:content.path("knowledge").path("modules"))for(JsonNode e:m.path("examples")){String next=uuid();examples.put(e.path("id").asText(),next);((ObjectNode)e).put("id",next);}cloneManuals(content,course,id,examples);for(JsonNode t:content.path("task-templates").path("templates"))((ObjectNode)t).put("id",uuid());}
        ObjectNode policy=(ObjectNode)content.path("assessment-policy");policy.put("id",uuid());policy.put("courseId",course);policy.put("releaseId",id);
        int version=jdbc.queryForObject("SELECT COALESCE(MAX(version_no),0)+1 FROM content_release WHERE course_id=?",Integer.class,course);jdbc.update("INSERT INTO content_release(id,course_id,version_no,state,source_sha,draft_content) VALUES(?,?,?,'DRAFT',?,?)",id,course,version,str(w,"sourceSha"),json(content));audit.add("RELEASE_CREATED","CONTENT_RELEASE",id,null,obj("courseId",course,"basedOnReleaseId",base));return releaseDto(raw(course,id,false));}
    private void replaceReferences(JsonNode node,Map<String,String> replacements){if(node.isObject()){var names=new ArrayList<String>();node.fieldNames().forEachRemaining(names::add);for(String field:names){JsonNode value=node.path(field);if(value.isTextual()&&replacements.containsKey(value.asText()))((ObjectNode)node).put(field,replacements.get(value.asText()));else replaceReferences(value,replacements);}}else if(node.isArray())for(JsonNode child:node)replaceReferences(child,replacements);}
    private void cloneManuals(ObjectNode content,String course,String release,Map<String,String> examples){Set<String> ids=new HashSet<>();content.findValues("fileId").stream().filter(JsonNode::isTextual).forEach(n->ids.add(n.asText()));Map<String,String> replacements=new HashMap<>();for(String id:ids){var f=files.row(id);if(!f.get("purpose").equals("MANUAL"))continue;var downloaded=files.download(id);JsonNode manifest=parse(new String(Base64.getDecoder().decode((String)downloaded.get("contentBase64")),StandardCharsets.UTF_8));if(manifest.isObject()&&manifest.has("sections")){((ObjectNode)manifest).put("courseId",course);((ObjectNode)manifest).put("releaseId",release);replaceReferences(manifest,examples);replacements.put(id,files.uploadJson(json(manifest).getBytes(StandardCharsets.UTF_8),(String)f.get("original_name")));}}replaceReferences(content,replacements);}
    public Object section(String course,String release,String section){var r=raw(course,release,false);if(r.get("state").equals("DRAFT")&&r.get("draft_content")!=null)return parse(r.get("draft_content")).path(section);
        return switch(section){
            case "catalog" -> catalog(course,release);
            case "knowledge" -> knowledge(course,release);
            case "questions" -> questions(course,release);
            case "task-templates" -> obj("templates",jdbc.queryForList("SELECT * FROM plan_task_template WHERE release_id=? AND course_id=? ORDER BY sort_order,id",release,course).stream().map(t->obj("id",t.get("id"),"kind",t.get("kind"),"title",t.get("title"),"estimatedMinutes",t.get("estimated_minutes"),"resource",parse(t.get("resource_locator")),"sortOrder",t.get("sort_order"))).toList());
            case "assessment-policy" -> policy(course,release);
            default -> throw new BusinessException(ErrorCode.NOT_FOUND);
        };}
    private Object catalog(String course,String release){List<Map<String,Object>> chapters=new ArrayList<>();for(var ch:jdbc.queryForList("SELECT r.*,c.stable_key FROM chapter_revision r JOIN chapter c ON c.id=r.chapter_id WHERE r.release_id=? AND r.course_id=? ORDER BY r.sort_order,r.chapter_id",release,course)){String id=(String)ch.get("chapter_id");var points=jdbc.queryForList("SELECT rp.*,p.stable_key FROM release_point rp JOIN knowledge_point p ON p.id=rp.point_id WHERE rp.release_id=? AND rp.chapter_id=? ORDER BY rp.point_id",release,id).stream().map(p->obj("id",p.get("point_id"),"stableKey",p.get("stable_key"),"title",p.get("title_snapshot"))).toList();var items=jdbc.queryForList("SELECT r.*,i.stable_key FROM item_revision r JOIN study_item i ON i.id=r.item_id WHERE r.release_id=? AND r.chapter_id=? ORDER BY r.sort_order,r.item_id",release,id).stream().map(i->obj("id",i.get("item_id"),"stableKey",i.get("stable_key"),"title",i.get("title"),"estimatedMinutes",i.get("estimated_minutes"),"resource",parse(i.get("resource_locator")),"sortOrder",i.get("sort_order"))).toList();chapters.add(obj("id",id,"stableKey",ch.get("stable_key"),"title",ch.get("title"),"sortOrder",ch.get("sort_order"),"participatesInAssessment",ch.get("participates_in_assessment"),"gateOverride",ch.get("gate_override"),"points",points,"items",items));}return obj("chapters",chapters);}
    private Object knowledge(String course,String release){return obj("modules",jdbc.queryForList("SELECT r.*,m.stable_key FROM module_revision r JOIN knowledge_module m ON m.id=r.module_id WHERE r.release_id=? AND m.course_id=? ORDER BY m.stable_key,m.id",release,course).stream().map(m->obj("id",m.get("module_id"),"stableKey",m.get("stable_key"),"title",m.get("title"),"content",m.get("content"),"difficulty",m.get("difficulty"),"formulas",parse(m.get("formulas")),"resources",parse(m.get("resources")),"examples",jdbc.queryForList("SELECT e.*,s.answer,s.solution FROM knowledge_example e JOIN example_solution s ON s.example_id=e.id WHERE e.release_id=? AND e.module_id=? ORDER BY e.sort_order,e.id",release,m.get("module_id")).stream().map(e->obj("id",e.get("id"),"stars",e.get("stars"),"question",e.get("question"),"answer",e.get("answer"),"solution",e.get("solution"),"sortOrder",e.get("sort_order"))).toList())).toList());}
    private Object questions(String course,String release){return obj("questions",jdbc.queryForList("SELECT q.*,r.stem,r.options,r.difficulty,r.source_locator,r.sort_order,r.id AS revision_id,s.correct_option,s.explanation FROM question q JOIN question_revision r ON r.question_id=q.id JOIN question_solution s ON s.revision_id=r.id WHERE q.course_id=? AND r.release_id=? ORDER BY r.sort_order,q.id",course,release).stream().map(q->{JsonNode options=parse(q.get("options"));return obj("id",q.get("id"),"originalKey",q.get("original_key"),"chapterId",q.get("chapter_id"),"eligibleOriginal",q.get("eligible_original"),"mode",q.get("mode"),"stem",q.get("stem"),"options",options,"difficulty",q.get("difficulty"),"pointIds",jdbc.queryForList("SELECT point_id FROM question_point WHERE revision_id=? ORDER BY point_id",String.class,q.get("revision_id")),"correctOption",q.get("correct_option"),"correctAnswer",options.path(((Number)q.get("correct_option")).intValue()).asText(),"explanation",q.get("explanation"),"sourceLocator",q.get("source_locator"),"sortOrder",q.get("sort_order"));}).toList());}
    private Object policy(String course,String release){var rows=jdbc.queryForList("SELECT * FROM assessment_policy WHERE course_id=? AND release_id=?",course,release);if(rows.isEmpty()){ObjectNode p=(ObjectNode)defaults(course).path("assessment-policy");p.put("releaseId",release);return p;}var r=rows.get(0);Map<String,Object> p=obj("id",r.get("id"),"courseId",course,"releaseId",release);for(String[] pair:POLICY_FIELDS)p.put(pair[0],r.get(pair[1]));p.put("weights",jdbc.queryForList("SELECT * FROM mock_chapter_weight WHERE policy_id=? ORDER BY chapter_id",r.get("id")).stream().map(w->obj("chapterId",w.get("chapter_id"),"scoreShare",w.get("score_share"),"sampleFrom",w.get("sample_from").toString(),"sampleTo",w.get("sample_to").toString(),"evidence",parse(w.get("evidence")),"approvedBy",w.get("approved_by"),"approvedAt",((LocalDateTime)w.get("approved_at")).toInstant(ZoneOffset.UTC))).toList());return p;}
    private static final String[][] POLICY_FIELDS={{"gateRatio","gate_ratio"},{"gateFloor","gate_floor"},{"gateCap","gate_cap"},{"chapterMinQuestions","chapter_min_questions"},{"chapterMaxQuestions","chapter_max_questions"},{"chapterLimitMinutes","chapter_limit_minutes"},{"chapterPassScore","chapter_pass_score"},{"mockQuestionCount","mock_question_count"},{"mockLimitMinutes","mock_limit_minutes"},{"mockPassScore","mock_pass_score"}};
    @Transactional public Object put(String course,String release,String section,JsonNode w){String schema=switch(section){case "catalog"->"CatalogDraft";case "knowledge"->"KnowledgeDraft";case "questions"->"QuestionBankDraft";case "task-templates"->"TemplateDraft";case "assessment-policy"->"AssessmentPolicyWrite";default->throw new BusinessException(ErrorCode.NOT_FOUND);};input.validate(schema,w);var row=raw(course,release,true);require(row.get("state").equals("DRAFT"),ErrorCode.CONFLICT,"已发布版本不能原地编辑");ObjectNode draft=(ObjectNode)parse(row.get("draft_content"));JsonNode stored=w.deepCopy();if(section.equals("assessment-policy")){ObjectNode p=(ObjectNode)stored;p.remove("confirmWeightReview");p.put("id",draft.path(section).path("id").asText(uuid()));p.put("courseId",course);p.put("releaseId",release);for(JsonNode weight:p.path("weights")){((ObjectNode)weight).put("approvedBy",CurrentUser.idOrThrow());((ObjectNode)weight).put("approvedAt",Instant.now().toString());}}
        draft.set(section,stored);jdbc.update("UPDATE content_release SET draft_content=? WHERE id=?",json(draft),release);audit.add("DRAFT_UPDATED","CONTENT_RELEASE",release,null,obj("courseId",course,"section",section));return stored;}
    private String normalize(String s){return Normalizer.normalize(s,Normalizer.Form.NFKC).replaceAll("(?U)\\s+","").trim();}
    public String fingerprint(JsonNode q){List<String> options=new ArrayList<>();q.path("options").forEach(o->options.add(normalize(o.asText())));Collections.sort(options);try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(json(List.of(normalize(str(q,"stem")),options)).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    public Map<String,Object> validation(String course,String release){var row=raw(course,release,false);ObjectNode draft=mapper.createObjectNode();for(String s:List.of("catalog","knowledge","questions","task-templates","assessment-policy"))draft.set(s,mapper.valueToTree(section(course,release,s)));List<Map<String,Object>> issues=new ArrayList<>();Map<String,String> points=new HashMap<>();Set<String> chapters=new HashSet<>(),ids=new HashSet<>(),fingerprints=new HashSet<>();int items=0;for(JsonNode ch:draft.path("catalog").path("chapters")){String id=str(ch,"id");if(!chapters.add(id))issue(issues,"DUPLICATE_ID","catalog","章节ID重复");for(JsonNode p:ch.path("points")){if(points.put(str(p,"id"),id)!=null)issue(issues,"DUPLICATE_ID","catalog","考点ID重复");}for(JsonNode i:ch.path("items")){items++;if(!ids.add(str(i,"id")))issue(issues,"DUPLICATE_ID","catalog","条目ID重复");resource(i.path("resource"),issues);}}
        Set<String> qids=new HashSet<>();Map<String,List<AssessmentPlanner.Candidate>> bank=new HashMap<>();for(JsonNode q:draft.path("questions").path("questions")){String id=str(q,"id"),chapter=str(q,"chapterId");if(!qids.add(id))issue(issues,"DUPLICATE_ID","questions","题目ID重复");if(!chapters.contains(chapter))issue(issues,"INVALID_MAPPING","questions","题目章节不属于本版");int correct=q.path("correctOption").asInt();if(correct>=q.path("options").size()||!q.path("options").path(correct).asText().equals(str(q,"correctAnswer")))issue(issues,"INVALID_ANSWER","questions","答案索引或文本不一致");Set<String> opts=new HashSet<>();for(JsonNode o:q.path("options"))if(!opts.add(normalize(o.asText())))issue(issues,"DUPLICATE_OPTION","questions","选项标准化后重复");String fp=fingerprint(q);if(!fingerprints.add(fp))issue(issues,"DUPLICATE_CONTENT","questions","不同题目内容重复");if(jdbc.queryForObject("SELECT COUNT(*) FROM question WHERE content_fingerprint=? AND id<>?",Integer.class,fp,id)>0)issue(issues,"DUPLICATE_CONTENT","questions","与现有稳定题目重复");Set<String> ps=new HashSet<>();for(JsonNode p:q.path("pointIds")){ps.add(p.asText());if(!chapter.equals(points.get(p.asText())))issue(issues,"INVALID_MAPPING","questions","考点不属于题目章节");}if(q.path("eligibleOriginal").asBoolean()&&q.path("mode").asText().equals("CHAPTER"))bank.computeIfAbsent(chapter,k->new ArrayList<>()).add(new AssessmentPlanner.Candidate(id,id,ps,false));}
        JsonNode p=draft.path("assessment-policy");if(p.path("gateFloor").asInt()>p.path("gateCap").asInt()||p.path("chapterMinQuestions").asInt()>p.path("chapterMaxQuestions").asInt())issue(issues,"INVALID_POLICY","assessment-policy","策略范围无效");
        for(JsonNode ch:draft.path("catalog").path("chapters"))if(ch.path("participatesInAssessment").asBoolean()){String id=str(ch,"id");List<String> ps=points.entrySet().stream().filter(e->e.getValue().equals(id)).map(Map.Entry::getKey).sorted().toList();int count=Math.max(p.path("chapterMinQuestions").asInt(),ps.size());if(count>p.path("chapterMaxQuestions").asInt())issue(issues,"TOO_MANY_POINTS","catalog","参与检测章考点超过题数上限");else try{AssessmentPlanner.chapter(ps,bank.getOrDefault(id,List.of()),count);}catch(IllegalArgumentException e){issue(issues,"INSUFFICIENT_QUESTIONS","questions",e.getMessage());}}
        for(JsonNode m:draft.path("knowledge").path("modules"))for(JsonNode r:m.path("resources"))resource(r,issues);for(JsonNode t:draft.path("task-templates").path("templates"))resource(t.path("resource"),issues);
        validateWeights(course,draft,issues);
        validateManuals(course,release,draft,issues);
        return obj("valid",issues.isEmpty(),"issues",issues,"contentCounts",obj("chapters",chapters.size(),"items",items,"points",points.size(),"questions",qids.size()));}
    private void validateWeights(String course,JsonNode draft,List<Map<String,Object>> issues){
        JsonNode weights=draft.path("assessment-policy").path("weights");if(weights.isEmpty())return;
        Set<String> expected=new HashSet<>(),actual=new HashSet<>();for(JsonNode c:draft.path("catalog").path("chapters"))if(c.path("participatesInAssessment").asBoolean())expected.add(str(c,"id"));
        java.math.BigDecimal total=java.math.BigDecimal.ZERO;String code=jdbc.queryForObject("SELECT code FROM course WHERE id=?",String.class,course);
        for(JsonNode w:weights){if(!actual.add(str(w,"chapterId")))issue(issues,"INVALID_POLICY","assessment-policy","章节权重重复");total=total.add(w.path("scoreShare").decimalValue());
            try{assessments.validateWeight(json(w.path("evidence")),code,LocalDate.parse(str(w,"sampleFrom")),LocalDate.parse(str(w,"sampleTo")),Instant.parse(str(w,"approvedAt")));}catch(RuntimeException e){issue(issues,"INVALID_POLICY","assessment-policy","模拟权重统计窗口、依据或审核时间无效");}}
        if(!actual.equals(expected)||total.compareTo(java.math.BigDecimal.ONE)!=0)issue(issues,"INVALID_POLICY","assessment-policy","模拟权重须覆盖参与章节且合计为1");
    }
    private void validateManuals(String course,String release,JsonNode draft,List<Map<String,Object>> issues){
        Set<String> fileIds=new HashSet<>(),examples=new HashSet<>();Map<String,Set<String>> chapterItems=new HashMap<>();
        for(JsonNode c:draft.path("catalog").path("chapters")){Set<String> items=new HashSet<>();for(JsonNode i:c.path("items"))items.add(str(i,"id"));chapterItems.put(str(c,"id"),items);}
        for(JsonNode m:draft.path("knowledge").path("modules"))for(JsonNode e:m.path("examples"))examples.add(str(e,"id"));
        draft.findValues("fileId").stream().filter(JsonNode::isTextual).forEach(n->fileIds.add(n.asText()));
        for(String file:fileIds)try{var r=files.row(file);if(!r.get("purpose").equals("MANUAL"))continue;
            JsonNode manifest=parse(new String(Base64.getDecoder().decode((String)files.download(file).get("contentBase64")),StandardCharsets.UTF_8));
            if(!course.equals(str(manifest,"courseId"))||!release.equals(str(manifest,"releaseId"))||!manifest.path("sections").isArray()||manifest.path("sections").isEmpty())throw new IllegalArgumentException();
            Set<String> seen=new HashSet<>();for(JsonNode section:manifest.path("sections")){String chapter=str(section,"chapterId");if(!seen.add(chapter)||!chapterItems.containsKey(chapter)||!section.path("title").isTextual()||!section.path("markdown").isTextual()||!section.path("exercises").isArray())throw new IllegalArgumentException();Set<String> seenItems=new HashSet<>();for(JsonNode e:section.path("exercises")){if(!chapterItems.get(chapter).contains(str(e,"itemId"))||!seenItems.add(str(e,"itemId"))||(str(e,"exampleId")!=null&&!examples.contains(str(e,"exampleId"))))throw new IllegalArgumentException();}}
        }catch(RuntimeException e){issue(issues,"INVALID_FILE","resource","手册文件损坏或发布、章节、练习映射无效");}
    }
    private void issue(List<Map<String,Object>> issues,String code,String path,String message){issues.add(obj("code",code,"path",path,"message",message));}
    private void resource(JsonNode r,List<Map<String,Object>> issues){if(r.isNull())return;if(r.path("kind").asText().equals("FILE")){String id=str(r,"fileId");if(id==null||jdbc.queryForObject("SELECT COUNT(*) FROM stored_file WHERE id=? AND purpose='MANUAL' AND state='ACTIVE'",Integer.class,id)==0)issue(issues,"INVALID_FILE","resource","手册文件无效");}else{String url=str(r,"url");if(url==null||!(url.startsWith("https://")||url.startsWith("http://")))issue(issues,"INVALID_RESOURCE","resource","资源链接必须为HTTP或HTTPS");}}
    private void stable(String table,String id,String ownerColumn,String owner,String key){var existing=jdbc.queryForList("SELECT "+ownerColumn+",stable_key FROM "+table+" WHERE id=?",id);if(existing.isEmpty()){if(table.equals("knowledge_point"))jdbc.update("INSERT INTO knowledge_point(id,chapter_id,stable_key,title) VALUES(?,?,?,?)",id,owner,key,key);else jdbc.update("INSERT INTO "+table+"(id,"+ownerColumn+",stable_key) VALUES(?,?,?)",id,owner,key);}else require(existing.get(0).get(ownerColumn).equals(owner)&&existing.get(0).get("stable_key").equals(key),ErrorCode.INVALID_RELATION,"稳定实体的归属和标识不能改变");}
    @Transactional public Object publish(String course,String release,JsonNode w){input.validate("OverrideConfirm",w);require(!jdbc.queryForList("SELECT id FROM course WHERE id=? FOR UPDATE",String.class,course).isEmpty(),ErrorCode.NOT_FOUND,"课程不存在");var row=raw(course,release,true);require(row.get("state").equals("DRAFT"),ErrorCode.CONFLICT,"仅草稿可以发布");var result=validation(course,release);require(Boolean.TRUE.equals(result.get("valid")),ErrorCode.INVALID_RELATION,"发布校验未通过，请读取validation明细");JsonNode draft=parse(row.get("draft_content"));
        for(JsonNode ch:draft.path("catalog").path("chapters")){String cid=str(ch,"id");stable("chapter",cid,"course_id",course,str(ch,"stableKey"));jdbc.update("INSERT INTO chapter_revision(release_id,chapter_id,course_id,title,sort_order,participates_in_assessment,gate_override) VALUES(?,?,?,?,?,?,?)",release,cid,course,str(ch,"title"),ch.path("sortOrder").asInt(),ch.path("participatesInAssessment").asBoolean(),value(ch,"gateOverride"));for(JsonNode p:ch.path("points")){stable("knowledge_point",str(p,"id"),"chapter_id",cid,str(p,"stableKey"));jdbc.update("INSERT INTO release_point(release_id,chapter_id,point_id,title_snapshot) VALUES(?,?,?,?)",release,cid,str(p,"id"),str(p,"title"));}for(JsonNode i:ch.path("items")){stable("study_item",str(i,"id"),"chapter_id",cid,str(i,"stableKey"));jdbc.update("INSERT INTO item_revision(release_id,item_id,chapter_id,title,resource_locator,estimated_minutes,sort_order) VALUES(?,?,?,?,?,?,?)",release,str(i,"id"),cid,str(i,"title"),i.path("resource").isNull()?null:json(i.path("resource")),i.path("estimatedMinutes").asInt(),i.path("sortOrder").asInt());}}
        for(JsonNode m:draft.path("knowledge").path("modules")){String mid=str(m,"id");stable("knowledge_module",mid,"course_id",course,str(m,"stableKey"));jdbc.update("INSERT INTO module_revision(release_id,module_id,title,content,difficulty,formulas,resources) VALUES(?,?,?,?,?,?,?)",release,mid,str(m,"title"),str(m,"content"),m.path("difficulty").asInt(),json(m.path("formulas")),json(m.path("resources")));for(JsonNode e:m.path("examples")){jdbc.update("INSERT INTO knowledge_example(id,release_id,module_id,stars,question,sort_order) VALUES(?,?,?,?,?,?)",str(e,"id"),release,mid,e.path("stars").asInt(),str(e,"question"),e.path("sortOrder").asInt());jdbc.update("INSERT INTO example_solution(example_id,answer,solution) VALUES(?,?,?)",str(e,"id"),str(e,"answer"),str(e,"solution"));}}
        for(JsonNode q:draft.path("questions").path("questions")){String id=str(q,"id"),revision=uuid(),fp=fingerprint(q);var old=jdbc.queryForList("SELECT * FROM question WHERE id=?",id);if(old.isEmpty())jdbc.update("INSERT INTO question(id,course_id,chapter_id,original_key,content_fingerprint,mode,eligible_original) VALUES(?,?,?,?,?,?,?)",id,course,str(q,"chapterId"),str(q,"originalKey"),fp,str(q,"mode"),q.path("eligibleOriginal").asBoolean());else{var existing=old.get(0);require(existing.get("course_id").equals(course)&&existing.get("chapter_id").equals(str(q,"chapterId"))&&existing.get("original_key").equals(str(q,"originalKey"))&&existing.get("mode").equals(str(q,"mode")),ErrorCode.INVALID_RELATION,"稳定题目归属或身份不能改变");jdbc.update("UPDATE question SET content_fingerprint=?,eligible_original=? WHERE id=?",fp,q.path("eligibleOriginal").asBoolean(),id);}jdbc.update("INSERT INTO question_revision(id,release_id,question_id,stem,options,difficulty,source_locator,sort_order) VALUES(?,?,?,?,?,?,?,?)",revision,release,id,str(q,"stem"),json(q.path("options")),q.path("difficulty").asInt(),str(q,"sourceLocator"),q.path("sortOrder").asInt());jdbc.update("INSERT INTO question_solution(revision_id,correct_option,explanation) VALUES(?,?,?)",revision,q.path("correctOption").asInt(),str(q,"explanation"));for(JsonNode p:q.path("pointIds"))jdbc.update("INSERT INTO question_point(revision_id,point_id) VALUES(?,?)",revision,p.asText());}
        for(JsonNode t:draft.path("task-templates").path("templates"))jdbc.update("INSERT INTO plan_task_template(id,release_id,course_id,kind,title,estimated_minutes,resource_locator,sort_order) VALUES(?,?,?,?,?,?,?,?)",str(t,"id"),release,course,str(t,"kind"),str(t,"title"),t.path("estimatedMinutes").asInt(),t.path("resource").isNull()?null:json(t.path("resource")),t.path("sortOrder").asInt());
        JsonNode policy=draft.path("assessment-policy");List<Object> args=new ArrayList<>(List.of(str(policy,"id"),course,release));for(String[] f:POLICY_FIELDS)args.add(value(policy,f[0]));jdbc.update("INSERT INTO assessment_policy(id,course_id,release_id,gate_ratio,gate_floor,gate_cap,chapter_min_questions,chapter_max_questions,chapter_limit_minutes,chapter_pass_score,mock_question_count,mock_limit_minutes,mock_pass_score) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",args.toArray());for(JsonNode weight:policy.path("weights"))jdbc.update("INSERT INTO mock_chapter_weight(policy_id,chapter_id,score_share,sample_from,sample_to,evidence,approved_by,approved_at) VALUES(?,?,?,?,?,?,?,?)",str(policy,"id"),str(weight,"chapterId"),value(weight,"scoreShare"),str(weight,"sampleFrom"),str(weight,"sampleTo"),json(weight.path("evidence")),str(weight,"approvedBy"),LocalDateTime.ofInstant(Instant.parse(str(weight,"approvedAt")),ZoneOffset.UTC));if(!policy.path("weights").isEmpty())assessments.weights(assessments.policy(course,release),assessments.participating(release));
        jdbc.update("UPDATE content_release SET state='RETIRED' WHERE course_id=? AND state='PUBLISHED'",course);jdbc.update("UPDATE content_release SET state='PUBLISHED',published_at=UTC_TIMESTAMP(6) WHERE id=?",release);audit.add("RELEASE_PUBLISHED","CONTENT_RELEASE",release,null,obj("courseId",course,"counts",result.get("contentCounts")));return releaseDto(raw(course,release,false));}
}
