package cn.xuexizhitu.service;
import cn.xuexizhitu.common.*;
import static cn.xuexizhitu.common.BusinessData.*;
import cn.xuexizhitu.repository.*;
import cn.xuexizhitu.security.CurrentUser;
import cn.xuexizhitu.validation.BusinessInput;
import com.fasterxml.jackson.databind.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class ExamService {
    private final JdbcTemplate jdbc;private final LearningRepository learning;private final AssessmentRepository assessments;private final AuditRepository audit;private final BusinessInput input;private final PrivateFileStore files;private final ObjectMapper mapper;
    public void authorized(String user,String course,String cycle){learning.requireCycleCourse(course,cycle);var c=learning.course(course);require(assessments.unlock(user,course,cycle,c.releaseId()).canWriteScores(),ErrorCode.EXAMS_LOCKED,"真题或成绩录入尚未解锁");}
    @Transactional public Object confirmOverride(String course,String cycle,JsonNode w){input.validate("OverrideConfirm",w);String user=CurrentUser.idOrThrow();learning.lockUser(user);learning.requireCycleCourse(course,cycle);var unlock=assessments.unlock(user,course,cycle,learning.course(course).releaseId());if(unlock.activeOverride()!=null)return unlock;
        require(unlock.skipWindow().canConfirm(),ErrorCode.INVALID_DATE,unlock.skipWindow().reason());String id=uuid();jdbc.update("INSERT INTO unlock_override(id,user_id,course_id,cycle_id,confirmed_at,exam_date_snapshot) VALUES(?,?,?,?,UTC_TIMESTAMP(6),?)",id,user,course,cycle,unlock.skipWindow().examDate());audit.add("OVERRIDE_CONFIRMED","UNLOCK_OVERRIDE",id,null,obj("courseId",course,"cycleId",cycle));return assessments.unlock(user,course,cycle,learning.course(course).releaseId());}
    @Transactional public Object revokeOverride(String course,String cycle,JsonNode w){input.validate("OverrideRevoke",w);String user=CurrentUser.idOrThrow();learning.lockUser(user);learning.requireCycleCourse(course,cycle);var active=assessments.unlock(user,course,cycle,learning.course(course).releaseId()).activeOverride();require(active!=null,ErrorCode.NOT_FOUND,"没有活动临考确认");require(active.revision()==w.path("expectedRevision").asLong(),ErrorCode.REVISION_CONFLICT,"临考确认修订号冲突");jdbc.update("UPDATE unlock_override SET revoked_at=UTC_TIMESTAMP(6),revision=revision+1 WHERE id=?",active.id());audit.add("OVERRIDE_REVOKED","UNLOCK_OVERRIDE",active.id(),null,obj("courseId",course,"cycleId",cycle));return assessments.unlock(user,course,cycle,learning.course(course).releaseId());}
    public Map<String,Object> paper(String course,String id){learning.course(course);var r=jdbc.queryForList("SELECT p.*,c.code FROM paper p JOIN course c ON c.id=p.course_id WHERE p.id=? AND p.course_id=?",id,course).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));return obj("id",id,"courseId",course,"paperKey",r.get("code")+":"+r.get("paper_month").toString().substring(0,7),"paperMonth",r.get("paper_month").toString().substring(0,7),"sourceCourseCode",r.get("source_course_code"),"questionFile",files.metadata((String)r.get("question_file_id")),"answerFile",r.get("answer_file_id")==null?null:files.metadata((String)r.get("answer_file_id")),"questionPages",r.get("question_pages"),"answerPages",r.get("answer_pages"),"note",r.get("note"));}
    public Object papers(String course,String cycle,int page,int size){learning.course(course);learning.requireCycleCourse(course,cycle);var ids=jdbc.queryForList("SELECT id FROM paper WHERE course_id=? ORDER BY paper_month DESC,id LIMIT ? OFFSET ?",String.class,course,size,(page-1L)*size);return obj("items",ids.stream().map(id->paper(course,id)).toList(),"page",page,"size",size,"total",jdbc.queryForObject("SELECT COUNT(*) FROM paper WHERE course_id=?",Long.class,course));}
    public Object paperFile(String course,String paper,String cycle,String part){String user=CurrentUser.idOrThrow();authorized(user,course,cycle);require(Set.of("QUESTION","ANSWER").contains(part),ErrorCode.INVALID_PARAMETER,"试卷部分无效");var p=paper(course,paper);Object metadata=p.get(part.equals("QUESTION")?"questionFile":"answerFile");require(metadata!=null,ErrorCode.NOT_FOUND,"参考答案文件未收录");String id=(String)((Map<?,?>)metadata).get("id");require(files.row(id).get("purpose").equals("PAPER"),ErrorCode.NOT_FOUND,"文件用途无效");return files.download(id);}
    private List<Map<String,Object>> records(String user,String course){return jdbc.query("SELECT s.*,p.paper_month,c.code FROM score_record s JOIN paper p ON p.id=s.paper_id JOIN course c ON c.id=s.course_id WHERE s.user_id=? AND s.course_id=? ORDER BY s.practiced_on,s.created_at,s.id",(r,i)->obj("id",r.getString("id"),"cycleId",r.getString("cycle_id"),"courseId",course,"paperId",r.getString("paper_id"),"paperKey",r.getString("code")+":"+r.getDate("paper_month").toLocalDate().toString().substring(0,7),"practicedOn",r.getDate("practiced_on").toLocalDate().toString(),"score",r.getBigDecimal("score"),"minutes",r.getInt("minutes"),"limitMinutes",r.getInt("limit_minutes"),"complete",r.getBoolean("complete"),"closedBook",r.getBoolean("closed_book"),"answersSeenBefore",r.getObject("answers_seen_before"),"source",r.getString("source"),"note",r.getString("note"),"createdAt",r.getObject("created_at",LocalDateTime.class).toInstant(ZoneOffset.UTC),"updatedAt",r.getObject("updated_at",LocalDateTime.class).toInstant(ZoneOffset.UTC),"revision",r.getLong("revision")),user,course);}
    private List<Map<String,Object>> scored(String course){learning.course(course);String user=CurrentUser.idOrThrow();var records=records(user,course);var analysis=ScoreAnalysis.analyze(course,records,today());for(var r:records){String id=(String)r.get("id");var reasons=analysis.reasons().get(id);r.put("images",jdbc.queryForList("SELECT i.file_id FROM score_record_image i JOIN stored_file f ON f.id=i.file_id WHERE i.score_record_id=? AND i.user_id=? AND f.state='ACTIVE' ORDER BY i.sort_order,i.file_id",String.class,id,user).stream().map(files::metadata).toList());r.put("eligibleConditionsMet",reasons.stream().noneMatch(s->Set.of("INCOMPLETE","OPEN_BOOK","OVERTIME","ANSWERS_SEEN","ANSWERS_STATE_UNKNOWN").contains(s)));r.put("selectedAsFirstValid",Objects.equals(id,analysis.firstIds().get(r.get("paperId"))));r.put("includedInPrediction",analysis.included().contains(id));r.put("firstValidRecordId",analysis.firstIds().get(r.get("paperId")));r.put("predictionExclusionReasons",reasons);}return records;}
    public Map<String,Object> score(String course,String id){return scored(course).stream().filter(r->r.get("id").equals(id)).findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
    public Object scores(String course,String cycle,String paper,int page,int size){if(cycle!=null)learning.requireCycleCourse(course,cycle);if(paper!=null)paper(course,paper);var list=new ArrayList<>(scored(course));Collections.reverse(list);list.removeIf(r->cycle!=null&&!r.get("cycleId").equals(cycle)||paper!=null&&!r.get("paperId").equals(paper));int start=(int)Math.min((page-1L)*size,list.size());return obj("items",list.subList(start,Math.min(start+size,list.size())),"page",page,"size",size,"total",list.size());}
    public Object prediction(String course){learning.course(course);return ScoreAnalysis.analyze(course,records(CurrentUser.idOrThrow(),course),today()).prediction();}
    public Object trend(String course,int limit){var list=new ArrayList<>(scored(course));Collections.reverse(list);return obj("courseId",course,"records",list.subList(0,Math.min(limit,list.size())));}
    @Transactional public Object writeScore(String course,String id,JsonNode w){input.validate(id==null?"ScoreWrite":"ScoreUpdate",w);String user=CurrentUser.idOrThrow();learning.lockUser(user);Map<String,Object> old=id==null?null:score(course,id);String cycle=old==null?str(w,"cycleId"):(String)old.get("cycleId"),paper=old==null?str(w,"paperId"):(String)old.get("paperId");authorized(user,course,cycle);paper(course,paper);LocalDate day=LocalDate.parse(str(w,"practicedOn"));require(!day.isAfter(today()),ErrorCode.INVALID_RELATION,"练习日期不能在未来");
        if(old==null){id=uuid();jdbc.update("INSERT INTO score_record(id,user_id,cycle_id,course_id,paper_id,practiced_on,score,minutes,limit_minutes,complete,closed_book,answers_seen_before,source,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'MANUAL',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",id,user,cycle,course,paper,day,value(w,"score"),w.path("minutes").asInt(),w.path("limitMinutes").asInt(),w.path("complete").asBoolean(),w.path("closedBook").asBoolean(),w.path("answersSeenBefore").asBoolean(),str(w,"note"));}
        else{require(((Number)old.get("revision")).longValue()==w.path("expectedRevision").asLong(),ErrorCode.REVISION_CONFLICT,"成绩修订号冲突");jdbc.update("UPDATE score_record SET practiced_on=?,score=?,minutes=?,limit_minutes=?,complete=?,closed_book=?,answers_seen_before=?,note=?,updated_at=UTC_TIMESTAMP(6),revision=revision+1 WHERE id=? AND user_id=?",day,value(w,"score"),w.path("minutes").asInt(),w.path("limitMinutes").asInt(),w.path("complete").asBoolean(),w.path("closedBook").asBoolean(),w.path("answersSeenBefore").asBoolean(),str(w,"note"),id,user);}
        return obj("record",score(course,id),"prediction",prediction(course),"unlock",assessments.unlock(user,course,cycle,learning.course(course).releaseId()));}
    @Transactional public Object uploadImage(String course,String score,MultipartFile file){String user=CurrentUser.idOrThrow();learning.lockUser(user);var r=score(course,score);authorized(user,course,(String)r.get("cycleId"));String id=files.upload(file,"SCORE_IMAGE",user,false);int order=jdbc.queryForObject("SELECT COALESCE(MAX(sort_order),-1)+1 FROM score_record_image WHERE score_record_id=?",Integer.class,score);jdbc.update("INSERT INTO score_record_image(user_id,score_record_id,file_id,sort_order) VALUES(?,?,?,?)",user,score,id,order);return files.metadata(id);}
    private void requireImage(String course,String score,String file){score(course,score);require(jdbc.queryForObject("SELECT COUNT(*) FROM score_record_image WHERE user_id=? AND score_record_id=? AND file_id=?",Integer.class,CurrentUser.idOrThrow(),score,file)>0,ErrorCode.NOT_FOUND,"附件不属于当前成绩");var r=files.row(file);require(r.get("purpose").equals("SCORE_IMAGE")&&CurrentUser.idOrThrow().equals(r.get("owner_id")),ErrorCode.NOT_FOUND,"附件不属于当前用户");}
    public Object image(String course,String score,String file){requireImage(course,score,file);return files.download(file);}
    @Transactional public Object deleteImage(String course,String score,String file){String user=CurrentUser.idOrThrow();learning.lockUser(user);requireImage(course,score,file);require(files.row(file).get("state").equals("ACTIVE"),ErrorCode.NOT_FOUND,"文件不可用");files.delete(file);audit.add("SCORE_IMAGE_DELETED","STORED_FILE",file,null,obj("scoreId",score));return obj("id",file,"state","DELETE_PENDING","downloadAllowed",false,"acceptedAt",Instant.now());}
}
