package cn.xuexizhitu.service;
import cn.xuexizhitu.common.*;
import static cn.xuexizhitu.common.BusinessData.*;
import cn.xuexizhitu.repository.*;
import cn.xuexizhitu.security.CurrentUser;
import cn.xuexizhitu.validation.BusinessInput;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class LegacyService {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;private final PrivateFileStore files;private final BusinessInput input;private final AuditRepository audit;private final LearningRepository learning;private final PracticeRepository practice;
    private JsonNode parse(Object v){try{return mapper.readTree(v.toString());}catch(Exception e){throw new IllegalStateException(e);}}
    private Map<String,Object> record(String id){return jdbc.queryForList("SELECT * FROM legacy_record WHERE id=? AND user_id=?",id,CurrentUser.idOrThrow()).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
    private String course(Map<String,Object> r){var reviews=jdbc.queryForList("SELECT course_id FROM legacy_pass_review WHERE legacy_record_id=?",String.class,r.get("id"));if(!reviews.isEmpty())return reviews.get(0);String id=parse(r.get("payload")).path("courseId").asText(null);return id!=null&&jdbc.queryForObject("SELECT COUNT(*) FROM course WHERE id=?",Integer.class,id)>0?id:null;}
    private Map<String,Object> summary(Map<String,Object> r){var payload=parse(r.get("payload"));String kind=(String)r.get("old_kind");if(!Set.of("ability","grading","sprint","practice","task","practice_request","other").contains(kind))kind="other";Instant created=null;try{created=Instant.parse(payload.path("createdAt").asText());}catch(Exception ignored){}return obj("id",r.get("id"),"kind",kind,"courseId",course(r),"title",payload.path("title").asText("旧"+kind+"记录"),"createdAt",created,"readOnly",true,"fileCount",jdbc.queryForObject("SELECT COUNT(*) FROM legacy_file_link l JOIN stored_file f ON f.id=l.file_id WHERE l.legacy_record_id=? AND f.state='ACTIVE'",Integer.class,r.get("id")));}
    public Object history(String kind,String course,int page,int size){require(kind==null||Set.of("ability","grading","sprint","practice","task","practice_request","other").contains(kind),ErrorCode.INVALID_PARAMETER,"历史类型无效");List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM legacy_record WHERE user_id=? ORDER BY id",CurrentUser.idOrThrow()).stream().map(this::summary).filter(r->(kind==null||kind.equals(r.get("kind")))&&(course==null||course.equals(r.get("courseId")))).toList();int start=(int)Math.min((page-1L)*size,rows.size());return obj("items",rows.subList(start,Math.min(start+size,rows.size())),"page",page,"size",size,"total",rows.size());}
    private JsonNode sanitize(JsonNode n){if(n.isArray()){ArrayNode result=mapper.createArrayNode();n.forEach(v->result.add(sanitize(v)));return result;}if(n.isObject()){ObjectNode result=mapper.createObjectNode();n.fields().forEachRemaining(e->{if(!e.getKey().toLowerCase(Locale.ROOT).matches(".*(password|token|storagekey|objectkey|signedurl|apikey).*"))result.set(e.getKey(),sanitize(e.getValue()));});return result;}return n;}
    public Object detail(String id){var r=record(id);JsonNode payload=parse(r.get("payload"));List<Map<String,Object>> errorList=new ArrayList<>();for(JsonNode e:payload.path("errors"))errorList.add(obj("question",e.path("question").asText(""),"reason",e.path("reason").asText(""),"deduction",e.path("deduction").isNumber()?e.path("deduction").decimalValue():null,"solution",e.path("solution").asText("")));Object oldScore=payload.path("score").isNumber()?payload.path("score").decimalValue():null;return obj("summary",summary(r),"oldId",r.get("old_id"),"oldStatus",payload.path("status").asText(null),"oldScore",oldScore,"summaryText",payload.path("summary").asText(null),"errors",errorList,"files",jdbc.queryForList("SELECT l.file_id FROM legacy_file_link l JOIN stored_file f ON f.id=l.file_id WHERE l.legacy_record_id=? AND f.owner_id=? AND f.state='ACTIVE' ORDER BY l.file_id",String.class,id,CurrentUser.idOrThrow()).stream().map(files::metadata).toList(),"passReview",jdbc.queryForList("SELECT id FROM legacy_pass_review WHERE legacy_record_id=? AND user_id=?",String.class,id,CurrentUser.idOrThrow()).stream().findFirst().map(this::review).orElse(null),"archivedContent",sanitize(payload).toPrettyString());}
    private void requireFile(String id,String file){record(id);require(jdbc.queryForObject("SELECT COUNT(*) FROM legacy_file_link l JOIN stored_file f ON f.id=l.file_id WHERE l.legacy_record_id=? AND l.file_id=? AND f.owner_id=? AND f.purpose='LEGACY_ATTACHMENT'",Integer.class,id,file,CurrentUser.idOrThrow())>0,ErrorCode.NOT_FOUND,"附件不属于此历史记录");}
    public Object file(String id,String file){requireFile(id,file);return files.download(file);}
    @Transactional public Object deleteFile(String id,String file){learning.lockUser(CurrentUser.idOrThrow());requireFile(id,file);require(files.row(file).get("state").equals("ACTIVE"),ErrorCode.NOT_FOUND,"文件不可用");files.delete(file);audit.add("LEGACY_ATTACHMENT_DELETED","STORED_FILE",file,null,obj("legacyRecordId",id));return obj("id",file,"state","DELETE_PENDING","downloadAllowed",false,"acceptedAt",Instant.now());}
    private Map<String,Object> reviewRow(String id,boolean lock){return jdbc.queryForList("SELECT * FROM legacy_pass_review WHERE id=? AND user_id=?"+(lock?" FOR UPDATE":""),id,CurrentUser.idOrThrow()).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
    public Map<String,Object> review(String id){var r=reviewRow(id,false);String oldVersion=parse(record((String)r.get("legacy_record_id")).get("payload")).path("version").asText(null);String pass=jdbc.queryForList("SELECT id FROM assessment_pass WHERE legacy_review_id=?",String.class,id).stream().findFirst().orElse(null);return obj("id",id,"legacyRecordId",r.get("legacy_record_id"),"courseId",r.get("course_id"),"chapterId",r.get("chapter_id"),"kind",r.get("kind"),"oldScore",r.get("old_score"),"oldThreshold",r.get("old_threshold"),"oldVersion",oldVersion,"mappingReleaseId",r.get("release_id"),"decision",r.get("decision"),"reason",r.get("reason"),"decidedAt",AdminService.instant(r,"decided_at"),"passId",pass);}
    public Object reviews(String decision,String course,int page,int size){require(decision==null||Set.of("PENDING","ACCEPT","REJECT").contains(decision),ErrorCode.INVALID_PARAMETER,"审核状态无效");var list=jdbc.queryForList("SELECT id FROM legacy_pass_review WHERE user_id=? ORDER BY id",String.class,CurrentUser.idOrThrow()).stream().map(this::review).filter(r->(decision==null||decision.equals(r.get("decision")))&&(course==null||course.equals(r.get("courseId")))).toList();int start=(int)Math.min((page-1L)*size,list.size());return obj("items",list.subList(start,Math.min(start+size,list.size())),"page",page,"size",size,"total",list.size());}
    @Transactional public Object decide(String id,JsonNode w){input.validate("LegacyReviewDecision",w);String user=CurrentUser.idOrThrow();learning.lockUser(user);var r=reviewRow(id,true);require(r.get("decision").equals("PENDING"),ErrorCode.CONFLICT,"审核已有终态");require(!str(w,"reason").isBlank(),ErrorCode.INVALID_PARAMETER,"审核原因不能为空");String course=str(w,"courseId"),release=str(w,"mappingReleaseId"),chapter=str(w,"chapterId");boolean accept=str(w,"decision").equals("ACCEPT");learning.course(course);require(r.get("course_id").equals(course),ErrorCode.INVALID_RELATION,"课程映射不一致");require((r.get("kind").equals("CHAPTER"))==(chapter!=null),ErrorCode.INVALID_RELATION,"章节映射与通过类型不一致");if(release!=null)require(jdbc.queryForObject("SELECT COUNT(*) FROM content_release WHERE id=? AND course_id=? AND state<>'DRAFT'",Integer.class,release,course)>0,ErrorCode.INVALID_RELATION,"发布映射无效");if(chapter!=null)require(release!=null&&jdbc.queryForObject("SELECT COUNT(*) FROM chapter_revision WHERE chapter_id=? AND release_id=? AND course_id=?",Integer.class,chapter,release,course)>0,ErrorCode.INVALID_RELATION,"章节映射无效");if(accept){require(release!=null,ErrorCode.INVALID_RELATION,"认领通过须有完整映射版本");require(new java.math.BigDecimal(r.get("old_score").toString()).compareTo(new java.math.BigDecimal(r.get("old_threshold").toString()))>=0,ErrorCode.INVALID_RELATION,"旧分数没有达到旧通过线");}
        jdbc.update("UPDATE legacy_pass_review SET course_id=?,chapter_id=?,release_id=?,decision=?,decided_by=?,decided_at=UTC_TIMESTAMP(6),reason=? WHERE id=?",course,chapter,release,str(w,"decision"),user,str(w,"reason"),id);if(accept)jdbc.update("INSERT INTO assessment_pass(id,user_id,course_id,chapter_id,kind,release_id,source,legacy_review_id,granted_at) VALUES(?,?,?,?,?,?,'LEGACY_CONFIRMED',?,UTC_TIMESTAMP(6))",uuid(),user,course,chapter,r.get("kind"),release,id);audit.add("LEGACY_PASS_REVIEWED","LEGACY_PASS_REVIEW",id,str(w,"reason"),obj("decision",str(w,"decision"),"courseId",course));return review(id);}
    public Object credits(String course,Boolean approved,int page,int size){var result=practice.legacy(CurrentUser.idOrThrow(),course,1,100);List<Object> filtered=new ArrayList<>();long count=0;int p=1;do{result=practice.legacy(CurrentUser.idOrThrow(),course,p++,100);for(var s:result.items())if(approved==null||s.gateCreditApproved()==approved){if(count>=(page-1L)*size&&filtered.size()<size)filtered.add(s);count++;}}while((p-1L)*100<result.total());return obj("items",filtered,"page",page,"size",size,"total",count);}
    @Transactional public Object credit(String id,JsonNode w){input.validate("LegacyPracticeCreditDecision",w);String user=CurrentUser.idOrThrow();learning.lockUser(user);var summaries=jdbc.queryForList("SELECT * FROM legacy_practice_summary WHERE legacy_record_id=? AND user_id=? FOR UPDATE",id,user);require(!summaries.isEmpty(),ErrorCode.NOT_FOUND,"旧汇总不属于本人");require(!str(w,"reason").isBlank(),ErrorCode.INVALID_PARAMETER,"认领原因不能为空");String question=str(w,"canonicalQuestionId");boolean approved=w.path("approved").asBoolean();require(!approved||question!=null,ErrorCode.INVALID_RELATION,"认领须有原创题映射");String course=null,chapter=null,release=null;if(question!=null){var rows=jdbc.queryForList("SELECT q.*,r.release_id FROM question q JOIN question_revision r ON r.question_id=q.id JOIN content_release cr ON cr.id=r.release_id AND cr.state='PUBLISHED' WHERE q.id=? AND q.mode='CHAPTER' AND q.eligible_original=true",question);require(!rows.isEmpty(),ErrorCode.INVALID_RELATION,"映射题目不是当前已审核原创题");var q=rows.get(0);course=(String)q.get("course_id");chapter=(String)q.get("chapter_id");release=(String)q.get("release_id");}else{String previous=(String)summaries.get(0).get("question_id");if(previous!=null){var q=jdbc.queryForMap("SELECT course_id,chapter_id FROM question WHERE id=?",previous);course=(String)q.get("course_id");chapter=(String)q.get("chapter_id");release=learning.course(course).releaseId();}}
        jdbc.update("UPDATE legacy_practice_summary SET question_id=?,gate_credit_approved=? WHERE legacy_record_id=? AND user_id=?",question,approved,id,user);audit.add("LEGACY_CREDIT_DECIDED","LEGACY_PRACTICE_SUMMARY",id,str(w,"reason"),obj("approved",approved,"questionId",question));var summary=practice.legacy(user,null,1,100).items().stream().filter(s->s.id().equals(id)).findFirst().orElseGet(()->{int p=2;while(true){var page=practice.legacy(user,null,p++,100);var found=page.items().stream().filter(s->s.id().equals(id)).findFirst();if(found.isPresent())return found.get();if(page.items().isEmpty())throw new BusinessException(ErrorCode.NOT_FOUND);}});require(course!=null&&release!=null,ErrorCode.INVALID_RELATION,"旧汇总缺少课程映射");return obj("summary",summary,"stats",practice.stats(user,course,release,chapter),"auditedAt",Instant.now());}
}
