package cn.xuexizhitu.contract;

// Generated by scripts/generate-workflow-dtos.py; run with --check in verification.
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.*;
import java.math.BigDecimal;
import java.util.*;

public final class WorkflowDtos {
    private WorkflowDtos() {}
    public record AdminKnowledgeExample(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="question",required=true) @NotNull @Size(min=1) @Valid String question,
            @JsonProperty(value="stars",required=true) @NotNull @Min(1L) @Max(5L) @Valid Integer stars,
            @JsonProperty(value="answer",required=true) @NotNull @Size(min=1) @Valid String answer,
            @JsonProperty(value="solution",required=true) @NotNull @Size(min=1) @Valid String solution,
            @JsonProperty(value="sortOrder",required=true) @NotNull @Min(0L) @Valid Integer sortOrder
    ) {}
    public record AdminQuestion(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="originalKey",required=true) @NotNull @Size(min=1,max=200) @Valid String originalKey,
            @JsonProperty(value="chapterId",required=true) @NotNull @Valid UUID chapterId,
            @JsonProperty(value="eligibleOriginal",required=true) @NotNull @Valid Boolean eligibleOriginal,
            @JsonProperty(value="mode",required=true) @NotNull @Pattern(regexp="^(?:CHAPTER|VARIANT)$") @Valid String mode,
            @JsonProperty(value="stem",required=true) @NotNull @Size(min=1) @Valid String stem,
            @JsonProperty(value="options",required=true) @NotNull @Size(min=2) @Valid List<@NotNull String> options,
            @JsonProperty(value="difficulty",required=true) @NotNull @Min(1L) @Max(5L) @Valid Integer difficulty,
            @JsonProperty(value="pointIds",required=true) @NotNull @Size(min=1) @Valid List<@NotNull UUID> pointIds,
            @JsonProperty(value="correctOption",required=true) @NotNull @Min(0L) @Valid Integer correctOption,
            @JsonProperty(value="correctAnswer",required=true) @NotNull @Valid String correctAnswer,
            @JsonProperty(value="explanation",required=true) @NotNull @Valid String explanation,
            @JsonProperty(value="sourceLocator",required=true) @Valid String sourceLocator,
            @JsonProperty(value="sortOrder",required=true) @NotNull @Min(0L) @Valid Integer sortOrder
    ) {}
    public record AssessmentPolicy(
            @JsonProperty(value="gateRatio",required=true) @NotNull @DecimalMin("0") @DecimalMax("1") @Valid BigDecimal gateRatio,
            @JsonProperty(value="gateFloor",required=true) @NotNull @Min(1L) @Valid Integer gateFloor,
            @JsonProperty(value="gateCap",required=true) @NotNull @Min(1L) @Valid Integer gateCap,
            @JsonProperty(value="chapterMinQuestions",required=true) @NotNull @Min(1L) @Valid Integer chapterMinQuestions,
            @JsonProperty(value="chapterMaxQuestions",required=true) @NotNull @Min(1L) @Valid Integer chapterMaxQuestions,
            @JsonProperty(value="chapterLimitMinutes",required=true) @NotNull @Min(1L) @Valid Integer chapterLimitMinutes,
            @JsonProperty(value="chapterPassScore",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal chapterPassScore,
            @JsonProperty(value="mockQuestionCount",required=true) @NotNull @Min(1L) @Valid Integer mockQuestionCount,
            @JsonProperty(value="mockLimitMinutes",required=true) @NotNull @Min(1L) @Valid Integer mockLimitMinutes,
            @JsonProperty(value="mockPassScore",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal mockPassScore,
            @JsonProperty(value="weights",required=true) @NotNull @Size(min=0) @Valid List<@NotNull MockWeightRead> weights,
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="releaseId",required=true) @NotNull @Valid UUID releaseId
    ) {}
    public record AssessmentPolicyWrite(
            @JsonProperty(value="gateRatio",required=true) @NotNull @DecimalMin("0") @DecimalMax("1") @Valid BigDecimal gateRatio,
            @JsonProperty(value="gateFloor",required=true) @NotNull @Min(1L) @Valid Integer gateFloor,
            @JsonProperty(value="gateCap",required=true) @NotNull @Min(1L) @Valid Integer gateCap,
            @JsonProperty(value="chapterMinQuestions",required=true) @NotNull @Min(1L) @Valid Integer chapterMinQuestions,
            @JsonProperty(value="chapterMaxQuestions",required=true) @NotNull @Min(1L) @Valid Integer chapterMaxQuestions,
            @JsonProperty(value="chapterLimitMinutes",required=true) @NotNull @Min(1L) @Valid Integer chapterLimitMinutes,
            @JsonProperty(value="chapterPassScore",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal chapterPassScore,
            @JsonProperty(value="mockQuestionCount",required=true) @NotNull @Min(1L) @Valid Integer mockQuestionCount,
            @JsonProperty(value="mockLimitMinutes",required=true) @NotNull @Min(1L) @Valid Integer mockLimitMinutes,
            @JsonProperty(value="mockPassScore",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal mockPassScore,
            @JsonProperty(value="weights",required=true) @NotNull @Size(min=0) @Valid List<@NotNull MockWeight> weights,
            @JsonProperty(value="confirmWeightReview",required=true) @NotNull @AssertTrue @Valid Boolean confirmWeightReview
    ) {}
    public record AuditEvent(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="actorId",required=true) @NotNull @Valid UUID actorId,
            @JsonProperty(value="action",required=true) @NotNull @Valid String action,
            @JsonProperty(value="targetType",required=true) @NotNull @Valid String targetType,
            @JsonProperty(value="targetId",required=true) @Valid UUID targetId,
            @JsonProperty(value="reason",required=true) @Valid String reason,
            @JsonProperty(value="details",required=true) @NotNull @Valid String details,
            @JsonProperty(value="occurredAt",required=true) @NotNull @Valid Instant occurredAt
    ) {}
    public record BankAlert(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId,
            @JsonProperty(value="releaseId",required=true) @NotNull @Valid UUID releaseId,
            @JsonProperty(value="alertCode",required=true) @NotNull @Pattern(regexp="^(?:INSUFFICIENT_QUESTIONS|POINT_NOT_COVERED|TOO_MANY_POINTS|MOCK_WEIGHTS_MISSING)$") @Valid String alertCode,
            @JsonProperty(value="message",required=true) @NotNull @Valid String message,
            @JsonProperty(value="createdAt",required=true) @NotNull @Valid Instant createdAt,
            @JsonProperty(value="acknowledgedAt",required=true) @Valid Instant acknowledgedAt
    ) {}
    public record CatalogDraft(
            @JsonProperty(value="chapters",required=true) @NotNull @Size(min=0) @Valid List<@NotNull ChapterDraft> chapters
    ) {}
    public record ChapterDraft(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="stableKey",required=true) @NotNull @Size(min=1,max=150) @Valid String stableKey,
            @JsonProperty(value="title",required=true) @NotNull @Size(min=1,max=250) @Valid String title,
            @JsonProperty(value="sortOrder",required=true) @NotNull @Min(0L) @Valid Integer sortOrder,
            @JsonProperty(value="participatesInAssessment",required=true) @NotNull @Valid Boolean participatesInAssessment,
            @JsonProperty(value="gateOverride",required=true) @Min(20L) @Max(100L) @Valid Integer gateOverride,
            @JsonProperty(value="points",required=true) @NotNull @Size(min=0) @Valid List<@NotNull PointDraft> points,
            @JsonProperty(value="items",required=true) @NotNull @Size(min=0) @Valid List<@NotNull ItemDraft> items
    ) {}
    public record ContentRelease(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="versionNo",required=true) @NotNull @Min(1L) @Valid Integer versionNo,
            @JsonProperty(value="state",required=true) @NotNull @Pattern(regexp="^(?:DRAFT|PUBLISHED|RETIRED)$") @Valid String state,
            @JsonProperty(value="publishedAt",required=true) @Valid Instant publishedAt,
            @JsonProperty(value="sourceSha",required=true) @Size(max=64) @Valid String sourceSha,
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) @Min(0L) @Valid Long draftRevision
    ) {}
    public record Countdown(
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="courseCode",required=true) @NotNull @Valid String courseCode,
            @JsonProperty(value="examDate",required=true) @Valid LocalDate examDate,
            @JsonProperty(value="daysRemaining",required=true) @Min(-100000L) @Valid Integer daysRemaining,
            @JsonProperty(value="status",required=true) @NotNull @Pattern(regexp="^(?:UPCOMING|TODAY|FINISHED|DATE_UNKNOWN)$") @Valid String status
    ) {}
    public record Course(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="code",required=true) @NotNull @Pattern(regexp="^[0-9]{5}$") @Valid String code,
            @JsonProperty(value="name",required=true) @NotNull @Valid String name,
            @JsonProperty(value="courseType",required=true) @NotNull @Pattern(regexp="^(?:THEORY|PRACTICE)$") @Valid String courseType,
            @JsonProperty(value="active",required=true) @NotNull @Valid Boolean active,
            @JsonProperty(value="releaseId",required=true) @Valid UUID releaseId,
            @JsonProperty(value="progress",required=true) @NotNull @Valid Progress progress,
            @JsonProperty(value="enrollment",required=true) @Valid Enrollment enrollment,
            @JsonProperty(value="capabilities",required=true) @NotNull @Valid CourseCapabilities capabilities
    ) {}
    public record CourseAdminWrite(
            @JsonProperty(value="code",required=true) @NotNull @Pattern(regexp="^(?:00023|02324|13175|13015|13216|13171)$") @Valid String code,
            @JsonProperty(value="name",required=true) @NotNull @Size(min=1,max=200) @Valid String name,
            @JsonProperty(value="courseType",required=true) @NotNull @Pattern(regexp="^(?:THEORY|PRACTICE)$") @Valid String courseType,
            @JsonProperty(value="active",required=true) @NotNull @Valid Boolean active
    ) {}
    public record CourseCapabilities(
            @JsonProperty(value="catalog",required=true) @NotNull @Valid Boolean catalog,
            @JsonProperty(value="knowledge",required=true) @NotNull @Valid Boolean knowledge,
            @JsonProperty(value="practice",required=true) @NotNull @Valid Boolean practice,
            @JsonProperty(value="exams",required=true) @NotNull @Valid Boolean exams,
            @JsonProperty(value="manual",required=true) @NotNull @Valid Boolean manual
    ) {}
    public record CycleCourse(
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="examDate",required=true) @Valid LocalDate examDate,
            @JsonProperty(value="startsAt",required=true) @Valid String startsAt,
            @JsonProperty(value="endsAt",required=true) @Valid String endsAt
    ) {}
    public record CycleWrite(
            @JsonProperty(value="name",required=true) @NotNull @Size(min=1,max=200) @Valid String name,
            @JsonProperty(value="startDate",required=true) @NotNull @Valid LocalDate startDate,
            @JsonProperty(value="endDate",required=true) @NotNull @Valid LocalDate endDate,
            @JsonProperty(value="courses",required=true) @NotNull @Size(min=0) @Valid List<@NotNull CycleCourse> courses
    ) {}
    public record Dashboard(
            @JsonProperty(value="snapshotId",required=true) @NotNull @Valid UUID snapshotId,
            @JsonProperty(value="asOf",required=true) @NotNull @Valid Instant asOf,
            @JsonProperty(value="localDate",required=true) @NotNull @Valid LocalDate localDate,
            @JsonProperty(value="cycle",required=true) @Valid ExamCycle cycle,
            @JsonProperty(value="continueLearning",required=true) @Valid LearningPosition continueLearning,
            @JsonProperty(value="todaySuggestion",required=true) @Valid Suggestion todaySuggestion,
            @JsonProperty(value="overallProgress",required=true) @NotNull @Valid Progress overallProgress,
            @JsonProperty(value="countdowns",required=true) @NotNull @Size(min=0) @Valid List<@NotNull Countdown> countdowns,
            @JsonProperty(value="courses",required=true) @NotNull @Size(min=0) @Valid List<@NotNull Course> courses,
            @JsonProperty(value="selectedPlanId",required=true) @Valid UUID selectedPlanId,
            @JsonProperty(value="todaySuggestionMessage",required=true) @NotNull @Valid String todaySuggestionMessage
    ) {}
    public record Enrollment(
            @JsonProperty(value="cycleId",required=true) @NotNull @Valid UUID cycleId,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="paid",required=true) @NotNull @Valid Boolean paid,
            @JsonProperty(value="fee",required=true) @DecimalMin("0") @DecimalMax("99999999.99") @Valid BigDecimal fee,
            @JsonProperty(value="officialScore",required=true) @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal officialScore,
            @JsonProperty(value="officialPassed",required=true) @Valid Boolean officialPassed,
            @JsonProperty(value="passedMonth",required=true) @Pattern(regexp="^\\d{4}-(0[1-9]|1[0-2])$") @Valid String passedMonth,
            @JsonProperty(value="note",required=true) @NotNull @Size(max=10000) @Valid String note,
            @JsonProperty(value="revision",required=true) @NotNull @Min(0L) @Valid Long revision
    ) {}
    public record ExamCycle(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="name",required=true) @NotNull @Valid String name,
            @JsonProperty(value="startDate",required=true) @NotNull @Valid LocalDate startDate,
            @JsonProperty(value="endDate",required=true) @NotNull @Valid LocalDate endDate,
            @JsonProperty(value="timezone",required=true) @NotNull @Pattern(regexp="^(?:Asia/Shanghai)$") @Valid String timezone,
            @JsonProperty(value="courses",required=true) @NotNull @Size(min=0) @Valid List<@NotNull CycleCourse> courses
    ) {}
    public record FileMetadata(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="name",required=true) @NotNull @Valid String name,
            @JsonProperty(value="mimeType",required=true) @NotNull @Valid String mimeType,
            @JsonProperty(value="sizeBytes",required=true) @NotNull @Min(1L) @Valid Integer sizeBytes,
            @JsonProperty(value="sha256",required=true) @NotNull @Pattern(regexp="^[0-9a-f]{64}$") @Valid String sha256,
            @JsonProperty(value="containsAnswers",required=true) @NotNull @Valid Boolean containsAnswers,
            @JsonProperty(value="state",required=true) @NotNull @Pattern(regexp="^(?:ACTIVE|DELETE_PENDING|DELETED)$") @Valid String state,
            @JsonProperty(value="purpose",required=true) @NotNull @Pattern(regexp="^(?:PAPER|MANUAL|SCORE_IMAGE|LEGACY_ATTACHMENT)$") @Valid String purpose
    ) {}
    public record Formula(
            @JsonProperty(value="label",required=true) @NotNull @Valid String label,
            @JsonProperty(value="tex",required=true) @NotNull @Valid String tex,
            @JsonProperty(value="condition",required=true) @NotNull @Valid String condition
    ) {}
    public record InvalidatePass(
            @JsonProperty(value="reason",required=true) @NotNull @Size(min=1) @Valid String reason,
            @JsonProperty(value="confirm",required=true) @NotNull @AssertTrue @Valid Boolean confirm
    ) {}
    public record ItemDraft(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="stableKey",required=true) @NotNull @Size(min=1,max=200) @Valid String stableKey,
            @JsonProperty(value="title",required=true) @NotNull @Size(min=1,max=300) @Valid String title,
            @JsonProperty(value="estimatedMinutes",required=true) @NotNull @Min(1L) @Valid Integer estimatedMinutes,
            @JsonProperty(value="resource",required=true) @Valid Resource resource,
            @JsonProperty(value="sortOrder",required=true) @NotNull @Min(0L) @Valid Integer sortOrder
    ) {}
    public record KnowledgeDraft(
            @JsonProperty(value="modules",required=true) @NotNull @Size(min=0) @Valid List<@NotNull KnowledgeDraftModulesItem> modules
    ) {}
    public record KnowledgeDraftModulesItem(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="stableKey",required=true) @NotNull @Size(min=1,max=150) @Valid String stableKey,
            @JsonProperty(value="title",required=true) @NotNull @Size(min=1,max=250) @Valid String title,
            @JsonProperty(value="content",required=true) @NotNull @Valid String content,
            @JsonProperty(value="difficulty",required=true) @NotNull @Min(1L) @Max(5L) @Valid Integer difficulty,
            @JsonProperty(value="formulas",required=true) @NotNull @Size(min=0) @Valid List<@NotNull Formula> formulas,
            @JsonProperty(value="resources",required=true) @NotNull @Size(min=0) @Valid List<@NotNull Resource> resources,
            @JsonProperty(value="examples",required=true) @NotNull @Size(min=0) @Valid List<@NotNull AdminKnowledgeExample> examples
    ) {}
    public record LearningPosition(
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="target",required=true) @NotNull @Valid Navigation target,
            @JsonProperty(value="title",required=true) @NotNull @Valid String title,
            @JsonProperty(value="updatedAt",required=true) @NotNull @Valid Instant updatedAt
    ) {}
    public record LegacyDetail(
            @JsonProperty(value="summary",required=true) @NotNull @Valid LegacyRecordSummary summary,
            @JsonProperty(value="oldId",required=true) @NotNull @Valid String oldId,
            @JsonProperty(value="oldStatus",required=true) @Valid String oldStatus,
            @JsonProperty(value="oldScore",required=true) @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal oldScore,
            @JsonProperty(value="summaryText",required=true) @Valid String summaryText,
            @JsonProperty(value="errors",required=true) @NotNull @Size(min=0) @Valid List<@NotNull LegacyError> errors,
            @JsonProperty(value="files",required=true) @NotNull @Size(min=0) @Valid List<@NotNull FileMetadata> files,
            @JsonProperty(value="passReview",required=true) @Valid LegacyPassReview passReview,
            @JsonProperty(value="archivedContent",required=true) @NotNull @Valid String archivedContent
    ) {}
    public record LegacyError(
            @JsonProperty(value="question",required=true) @NotNull @Valid String question,
            @JsonProperty(value="reason",required=true) @NotNull @Valid String reason,
            @JsonProperty(value="deduction",required=true) @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal deduction,
            @JsonProperty(value="solution",required=true) @NotNull @Valid String solution
    ) {}
    public record LegacyPassReview(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="legacyRecordId",required=true) @NotNull @Valid UUID legacyRecordId,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId,
            @JsonProperty(value="kind",required=true) @NotNull @Pattern(regexp="^(?:CHAPTER|MOCK)$") @Valid String kind,
            @JsonProperty(value="oldScore",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal oldScore,
            @JsonProperty(value="oldThreshold",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal oldThreshold,
            @JsonProperty(value="oldVersion",required=true) @Valid String oldVersion,
            @JsonProperty(value="mappingReleaseId",required=true) @Valid UUID mappingReleaseId,
            @JsonProperty(value="decision",required=true) @NotNull @Pattern(regexp="^(?:PENDING|ACCEPT|REJECT)$") @Valid String decision,
            @JsonProperty(value="reason",required=true) @Valid String reason,
            @JsonProperty(value="decidedAt",required=true) @Valid Instant decidedAt,
            @JsonProperty(value="passId",required=true) @Valid UUID passId
    ) {}
    public record LegacyPracticeCreditDecision(
            @JsonProperty(value="approved",required=true) @NotNull @Valid Boolean approved,
            @JsonProperty(value="canonicalQuestionId",required=true) @Valid UUID canonicalQuestionId,
            @JsonProperty(value="reason",required=true) @NotNull @Size(min=1) @Valid String reason,
            @JsonProperty(value="confirm",required=true) @NotNull @AssertTrue @Valid Boolean confirm
    ) {}
    public record LegacyPracticeCreditResult(
            @JsonProperty(value="summary",required=true) @NotNull @Valid LegacyPracticeSummary summary,
            @JsonProperty(value="stats",required=true) @NotNull @Valid PracticeStats stats,
            @JsonProperty(value="auditedAt",required=true) @NotNull @Valid Instant auditedAt
    ) {}
    public record LegacyPracticeSummary(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="questionId",required=true) @Valid UUID questionId,
            @JsonProperty(value="oldQuestionId",required=true) @NotNull @Valid String oldQuestionId,
            @JsonProperty(value="attempts",required=true) @Min(1L) @Valid Integer attempts,
            @JsonProperty(value="selectedOption",required=true) @Min(0L) @Valid Integer selectedOption,
            @JsonProperty(value="correct",required=true) @Valid Boolean correct,
            @JsonProperty(value="lastUpdatedAt",required=true) @Valid Instant lastUpdatedAt,
            @JsonProperty(value="gateCreditApproved",required=true) @NotNull @Valid Boolean gateCreditApproved,
            @JsonProperty(value="courseId",required=true) @Valid UUID courseId,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId
    ) {}
    public record LegacyRecordSummary(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="kind",required=true) @NotNull @Pattern(regexp="^(?:ability|grading|sprint|practice|task|practice_request|other)$") @Valid String kind,
            @JsonProperty(value="courseId",required=true) @Valid UUID courseId,
            @JsonProperty(value="title",required=true) @NotNull @Valid String title,
            @JsonProperty(value="createdAt",required=true) @Valid Instant createdAt,
            @JsonProperty(value="readOnly",required=true) @NotNull @AssertTrue @Valid Boolean readOnly,
            @JsonProperty(value="fileCount",required=true) @NotNull @Min(0L) @Valid Integer fileCount
    ) {}
    public record LegacyReviewDecision(
            @JsonProperty(value="decision",required=true) @NotNull @Pattern(regexp="^(?:ACCEPT|REJECT)$") @Valid String decision,
            @JsonProperty(value="reason",required=true) @NotNull @Size(min=1) @Valid String reason,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId,
            @JsonProperty(value="mappingReleaseId",required=true) @Valid UUID mappingReleaseId
    ) {}
    public record MockWeight(
            @JsonProperty(value="chapterId",required=true) @NotNull @Valid UUID chapterId,
            @JsonProperty(value="scoreShare",required=true) @NotNull @DecimalMin("0") @DecimalMax("1") @Valid BigDecimal scoreShare,
            @JsonProperty(value="sampleFrom",required=true) @NotNull @Valid LocalDate sampleFrom,
            @JsonProperty(value="sampleTo",required=true) @NotNull @Valid LocalDate sampleTo,
            @JsonProperty(value="evidence",required=true) @NotNull @Valid MockWeightEvidence evidence
    ) {}
    public record MockWeightEvidence(
            @JsonProperty(value="description",required=true) @NotNull @Size(min=1) @Valid String description,
            @JsonProperty(value="sourcePaperKeys",required=true) @NotNull @Size(min=1) @Valid List<@NotNull String> sourcePaperKeys
    ) {}
    public record MockWeightRead(
            @JsonProperty(value="chapterId",required=true) @NotNull @Valid UUID chapterId,
            @JsonProperty(value="scoreShare",required=true) @NotNull @DecimalMin("0") @DecimalMax("1") @Valid BigDecimal scoreShare,
            @JsonProperty(value="sampleFrom",required=true) @NotNull @Valid LocalDate sampleFrom,
            @JsonProperty(value="sampleTo",required=true) @NotNull @Valid LocalDate sampleTo,
            @JsonProperty(value="evidence",required=true) @NotNull @Valid MockWeightReadEvidence evidence,
            @JsonProperty(value="approvedBy",required=true) @NotNull @Valid UUID approvedBy,
            @JsonProperty(value="approvedAt",required=true) @NotNull @Valid Instant approvedAt
    ) {}
    public record MockWeightReadEvidence(
            @JsonProperty(value="description",required=true) @NotNull @Size(min=1) @Valid String description,
            @JsonProperty(value="sourcePaperKeys",required=true) @NotNull @Size(min=1) @Valid List<@NotNull String> sourcePaperKeys
    ) {}
    public record Navigation(
            @JsonProperty(value="pane",required=true) @NotNull @Pattern(regexp="^(?:CATALOG|KNOWLEDGE|PRACTICE|EXAMS|NOTES|MANUAL)$") @Valid String pane,
            @JsonProperty(value="courseCode",required=true) @NotNull @Pattern(regexp="^[0-9]{5}$") @Valid String courseCode,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId,
            @JsonProperty(value="itemId",required=true) @Valid UUID itemId,
            @JsonProperty(value="questionId",required=true) @Valid UUID questionId
    ) {}
    public record PaperWrite(
            @JsonProperty(value="paperMonth",required=true) @NotNull @Pattern(regexp="^\\d{4}-(0[1-9]|1[0-2])$") @Valid String paperMonth,
            @JsonProperty(value="sourceCourseCode",required=true) @Size(max=20) @Valid String sourceCourseCode,
            @JsonProperty(value="questionFileId",required=true) @NotNull @Valid UUID questionFileId,
            @JsonProperty(value="answerFileId",required=true) @Valid UUID answerFileId,
            @JsonProperty(value="questionPages",required=true) @Min(1L) @Valid Integer questionPages,
            @JsonProperty(value="answerPages",required=true) @Min(1L) @Valid Integer answerPages,
            @JsonProperty(value="note",required=true) @NotNull @Valid String note
    ) {}
    public record Pass(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="kind",required=true) @NotNull @Pattern(regexp="^(?:CHAPTER|MOCK)$") @Valid String kind,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId,
            @JsonProperty(value="releaseId",required=true) @NotNull @Valid UUID releaseId,
            @JsonProperty(value="source",required=true) @NotNull @Pattern(regexp="^(?:ASSESSMENT|LEGACY_CONFIRMED)$") @Valid String source,
            @JsonProperty(value="grantedAt",required=true) @NotNull @Valid Instant grantedAt,
            @JsonProperty(value="invalidatedAt",required=true) @Valid Instant invalidatedAt,
            @JsonProperty(value="invalidatedBy",required=true) @Valid UUID invalidatedBy,
            @JsonProperty(value="invalidationReason",required=true) @Valid String invalidationReason
    ) {}
    public record PassInvalidationResult(
            @JsonProperty(value="pass",required=true) @NotNull @Valid Pass pass,
            @JsonProperty(value="affectedUnlocks",required=true) @NotNull @Size(min=0) @Valid List<@NotNull Unlock> affectedUnlocks,
            @JsonProperty(value="evaluatedAt",required=true) @NotNull @Valid Instant evaluatedAt
    ) {}
    public record Plan(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="revision",required=true) @NotNull @Min(1L) @Valid Long revision,
            @JsonProperty(value="config",required=true) @NotNull @Valid PlanConfig config,
            @JsonProperty(value="tasks",required=true) @NotNull @Size(min=0) @Valid List<@NotNull PlanTask> tasks,
            @JsonProperty(value="days",required=true) @NotNull @Size(min=0) @Valid List<@NotNull PlanDay> days,
            @JsonProperty(value="unscheduled",required=true) @NotNull @Size(min=0) @Valid List<@NotNull TaskSegment> unscheduled,
            @JsonProperty(value="awaitingDate",required=true) @NotNull @Size(min=0) @Valid List<@NotNull TaskSegment> awaitingDate,
            @JsonProperty(value="progress",required=true) @NotNull @Valid PlanProgress progress,
            @JsonProperty(value="createdAt",required=true) @NotNull @Valid Instant createdAt,
            @JsonProperty(value="confirmedAt",required=true) @Valid Instant confirmedAt,
            @JsonProperty(value="asOf",required=true) @NotNull @Valid Instant asOf,
            @JsonProperty(value="weeks",required=true) @NotNull @Size(min=0) @Valid List<@NotNull PlanWeek> weeks,
            @JsonProperty(value="completedDayCount",required=true) @NotNull @Min(0L) @Valid Integer completedDayCount,
            @JsonProperty(value="dayCount",required=true) @NotNull @Min(0L) @Valid Integer dayCount,
            @JsonProperty(value="overdueUncompletedMinutes",required=true) @NotNull @Min(0L) @Valid Integer overdueUncompletedMinutes,
            @JsonProperty(value="courseSummaries",required=true) @NotNull @Size(min=0) @Valid List<@NotNull Course> courseSummaries
    ) {}
    public record PlanConfig(
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) @Size(min=1,max=100) @Valid String name,
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) @Pattern(regexp="^(?:SEQUENTIAL|WEEKLY_35)$") @Valid String strategy,
            @JsonProperty(value="cycleId",required=true) @NotNull @Valid UUID cycleId,
            @JsonProperty(value="startDate",required=true) @NotNull @Valid LocalDate startDate,
            @JsonProperty(value="endDate",required=true) @NotNull @Valid LocalDate endDate,
            @JsonProperty(value="coursePriority",required=true) @NotNull @Size(min=1) @Valid List<@NotNull UUID> coursePriority,
            @JsonProperty(value="dayCapacities",required=true) @NotNull @Size(min=1) @Valid List<@NotNull PlanConfigDayCapacitiesItem> dayCapacities,
            @JsonProperty(value="courseScope",required=true) @NotNull @Size(min=1) @Valid List<@NotNull UUID> courseScope
    ) {}
    public record PlanConfigDayCapacitiesItem(
            @JsonProperty(value="day",required=true) @NotNull @Valid LocalDate day,
            @JsonProperty(value="capacityMinutes",required=true) @NotNull @Min(0L) @Max(1440L) @Valid Integer capacityMinutes
    ) {}
    public record PlanCreate(
            @JsonProperty(value="config",required=true) @NotNull @Valid PlanConfig config,
            @JsonProperty(value="acceptUnscheduled",required=true) @NotNull @Valid Boolean acceptUnscheduled
    ) {}
    public record PlanDay(
            @JsonProperty(value="day",required=true) @NotNull @Valid LocalDate day,
            @JsonProperty(value="capacityMinutes",required=true) @NotNull @Min(0L) @Max(1440L) @Valid Integer capacityMinutes,
            @JsonProperty(value="reservedMinutes",required=true) @NotNull @Min(0L) @Valid Integer reservedMinutes,
            @JsonProperty(value="remainingMinutes",required=true) @NotNull @Min(0L) @Valid Integer remainingMinutes,
            @JsonProperty(value="segments",required=true) @NotNull @Size(min=0) @Valid List<@NotNull TaskSegment> segments,
            @JsonProperty(value="completedMinutes",required=true) @NotNull @Min(0L) @Valid Integer completedMinutes,
            @JsonProperty(value="percent",required=true) @NotNull @Min(0L) @Max(100L) @Valid Integer percent
    ) {}
    public record PlanPreview(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="planId",required=true) @NotNull @Valid UUID planId,
            @JsonProperty(value="baseRevision",required=true) @NotNull @Min(1L) @Valid Long baseRevision,
            @JsonProperty(value="asOf",required=true) @NotNull @Valid LocalDate asOf,
            @JsonProperty(value="inputFingerprint",required=true) @NotNull @Pattern(regexp="^[0-9a-f]{64}$") @Valid String inputFingerprint,
            @JsonProperty(value="proposedPlan",required=true) @NotNull @Valid Plan proposedPlan,
            @JsonProperty(value="moves",required=true) @NotNull @Size(min=0) @Valid List<@NotNull PlanPreviewMovesItem> moves,
            @JsonProperty(value="gapMinutes",required=true) @NotNull @Min(0L) @Valid Integer gapMinutes,
            @JsonProperty(value="gapHours",required=true) @NotNull @DecimalMin("0") @DecimalMax("100000") @Valid BigDecimal gapHours,
            @JsonProperty(value="options",required=true) @NotNull @Size(min=0) @Valid List<@NotNull String> options,
            @JsonProperty(value="createdAt",required=true) @NotNull @Valid Instant createdAt
    ) {}
    public record PlanPreviewMovesItem(
            @JsonProperty(value="segmentId",required=true) @NotNull @Valid UUID segmentId,
            @JsonProperty(value="fromDate",required=true) @NotNull @Valid LocalDate fromDate,
            @JsonProperty(value="toSegments",required=true) @NotNull @Size(min=0) @Valid List<@NotNull TaskSegment> toSegments
    ) {}
    public record PlanProgress(
            @JsonProperty(value="completedMinutes",required=true) @NotNull @Min(0L) @Valid Integer completedMinutes,
            @JsonProperty(value="totalEstimatedMinutes",required=true) @NotNull @Min(0L) @Valid Integer totalEstimatedMinutes,
            @JsonProperty(value="percent",required=true) @NotNull @Min(0L) @Max(100L) @Valid Integer percent
    ) {}
    public record PlanSummary(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="cycleId",required=true) @NotNull @Valid UUID cycleId,
            @JsonProperty(value="startDate",required=true) @NotNull @Valid LocalDate startDate,
            @JsonProperty(value="endDate",required=true) @NotNull @Valid LocalDate endDate,
            @JsonProperty(value="revision",required=true) @NotNull @Min(1L) @Valid Long revision,
            @JsonProperty(value="completedPercent",required=true) @NotNull @Min(0L) @Max(100L) @Valid Integer completedPercent
    ) {}
    public record PlanTask(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="itemId",required=true) @Valid UUID itemId,
            @JsonProperty(value="templateId",required=true) @Valid UUID templateId,
            @JsonProperty(value="kind",required=true) @NotNull @Pattern(regexp="^(?:ITEM|PAPER|REVIEW)$") @Valid String kind,
            @JsonProperty(value="title",required=true) @NotNull @Valid String title,
            @JsonProperty(value="estimatedMinutes",required=true) @NotNull @Min(1L) @Valid Integer estimatedMinutes,
            @JsonProperty(value="releaseId",required=true) @NotNull @Valid UUID releaseId,
            @JsonProperty(value="completed",required=true) @NotNull @Valid Boolean completed,
            @JsonProperty(value="completedAt",required=true) @Valid Instant completedAt,
            @JsonProperty(value="target",required=true) @NotNull @Valid Navigation target
    ) {}
    public record PlanWeek(
            @JsonProperty(value="index",required=true) @NotNull @Min(1L) @Valid Integer index,
            @JsonProperty(value="startDate",required=true) @NotNull @Valid LocalDate startDate,
            @JsonProperty(value="endDate",required=true) @NotNull @Valid LocalDate endDate,
            @JsonProperty(value="scheduledMinutes",required=true) @NotNull @Min(0L) @Valid Integer scheduledMinutes,
            @JsonProperty(value="completedMinutes",required=true) @NotNull @Min(0L) @Valid Integer completedMinutes,
            @JsonProperty(value="percent",required=true) @NotNull @Min(0L) @Max(100L) @Valid Integer percent
    ) {}
    public record PointDraft(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="stableKey",required=true) @NotNull @Size(min=1,max=150) @Valid String stableKey,
            @JsonProperty(value="title",required=true) @NotNull @Size(min=1,max=250) @Valid String title
    ) {}
    public record PracticeStats(
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="chapterId",required=true) @Valid UUID chapterId,
            @JsonProperty(value="availableOriginalCount",required=true) @NotNull @Min(0L) @Valid Integer availableOriginalCount,
            @JsonProperty(value="answeredOriginalCount",required=true) @NotNull @Min(0L) @Valid Integer answeredOriginalCount,
            @JsonProperty(value="practiceAttemptCount",required=true) @NotNull @Min(0L) @Valid Integer practiceAttemptCount,
            @JsonProperty(value="practiceCorrectCount",required=true) @NotNull @Min(0L) @Valid Integer practiceCorrectCount,
            @JsonProperty(value="practiceAccuracy",required=true) @NotNull @DecimalMin("0") @DecimalMax("100") @Valid BigDecimal practiceAccuracy,
            @JsonProperty(value="latestWrongCount",required=true) @NotNull @Min(0L) @Valid Integer latestWrongCount,
            @JsonProperty(value="gateThreshold",required=true) @Min(0L) @Valid Integer gateThreshold,
            @JsonProperty(value="canApplyChapterAssessment",required=true) @Valid Boolean canApplyChapterAssessment,
            @JsonProperty(value="blockReasons",required=true) @NotNull @Size(min=0) @Valid List<@NotNull String> blockReasons
    ) {}
    public record PreviewConfirm(
            @JsonProperty(value="baseRevision",required=true) @NotNull @Min(1L) @Valid Long baseRevision,
            @JsonProperty(value="inputFingerprint",required=true) @NotNull @Pattern(regexp="^[0-9a-f]{64}$") @Valid String inputFingerprint,
            @JsonProperty(value="acceptUnscheduled",required=true) @NotNull @Valid Boolean acceptUnscheduled,
            @JsonProperty(value="confirm",required=true) @NotNull @AssertTrue @Valid Boolean confirm
    ) {}
    public record Progress(
            @JsonProperty(value="completedItems",required=true) @NotNull @Min(0L) @Valid Integer completedItems,
            @JsonProperty(value="totalItems",required=true) @NotNull @Min(0L) @Valid Integer totalItems,
            @JsonProperty(value="percent",required=true) @NotNull @Min(0L) @Max(100L) @Valid Integer percent
    ) {}
    public record QuestionBankDraft(
            @JsonProperty(value="questions",required=true) @NotNull @Size(min=0) @Valid List<@NotNull AdminQuestion> questions
    ) {}
    public record ReleaseCreate(
            @JsonProperty(value="basedOnReleaseId",required=true) @Valid UUID basedOnReleaseId,
            @JsonProperty(value="sourceSha",required=true) @Size(max=64) @Valid String sourceSha
    ) {}
    public record ReleaseValidation(
            @JsonProperty(value="valid",required=true) @NotNull @Valid Boolean valid,
            @JsonProperty(value="issues",required=true) @NotNull @Size(min=0) @Valid List<@NotNull ReleaseValidationIssuesItem> issues,
            @JsonProperty(value="contentCounts",required=true) @NotNull @Valid ReleaseValidationContentCounts contentCounts
    ) {}
    public record ReleaseValidationContentCounts(
            @JsonProperty(value="chapters",required=true) @NotNull @Min(0L) @Valid Integer chapters,
            @JsonProperty(value="items",required=true) @NotNull @Min(0L) @Valid Integer items,
            @JsonProperty(value="points",required=true) @NotNull @Min(0L) @Valid Integer points,
            @JsonProperty(value="questions",required=true) @NotNull @Min(0L) @Valid Integer questions
    ) {}
    public record ReleaseValidationIssuesItem(
            @JsonProperty(value="code",required=true) @NotNull @Valid String code,
            @JsonProperty(value="path",required=true) @NotNull @Valid String path,
            @JsonProperty(value="message",required=true) @NotNull @Valid String message
    ) {}
    public record RescheduleRequest(
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) @Valid PlanConfig config,
            @JsonProperty(value="baseRevision",required=true) @NotNull @Min(1L) @Valid Long baseRevision,
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) @Size(min=0) @Valid List<@NotNull RescheduleRequestDayCapacitiesItem> dayCapacities,
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) @Size(min=0) @Valid List<@NotNull UUID> coursePriority
    ) {}
    public record RescheduleRequestDayCapacitiesItem(
            @JsonProperty(value="day",required=true) @NotNull @Valid LocalDate day,
            @JsonProperty(value="capacityMinutes",required=true) @NotNull @Min(0L) @Max(1440L) @Valid Integer capacityMinutes
    ) {}
    public record Resource(
            @JsonProperty(value="kind",required=true) @NotNull @Pattern(regexp="^(?:LINK|FILE)$") @Valid String kind,
            @JsonProperty(value="label",required=true) @NotNull @Valid String label,
            @JsonProperty(value="url",required=true) @Valid String url,
            @JsonProperty(value="fileId",required=true) @Valid UUID fileId
    ) {}
    public record Suggestion(
            @JsonProperty(value="title",required=true) @NotNull @Valid String title,
            @JsonProperty(value="reason",required=true) @NotNull @Valid String reason,
            @JsonProperty(value="taskId",required=true) @Valid UUID taskId,
            @JsonProperty(value="target",required=true) @NotNull @Valid Navigation target
    ) {}
    public record TaskCompletion(
            @JsonProperty(value="task",required=true) @NotNull @Valid PlanTask task,
            @JsonProperty(value="planRevision",required=true) @NotNull @Min(1L) @Valid Long planRevision,
            @JsonProperty(value="courseProgress",required=true) @NotNull @Valid Progress courseProgress,
            @JsonProperty(value="overallProgress",required=true) @NotNull @Valid Progress overallProgress,
            @JsonProperty(value="affectedPlanIds",required=true) @NotNull @Size(min=0) @Valid List<@NotNull UUID> affectedPlanIds,
            @JsonProperty(value="clientMutationId",required=true) @NotNull @Valid UUID clientMutationId,
            @JsonProperty(value="asOf",required=true) @NotNull @Valid Instant asOf
    ) {}
    public record TaskCompletionWrite(
            @JsonProperty(value="completed",required=true) @NotNull @Valid Boolean completed,
            @JsonProperty(value="expectedCompleted",required=true) @NotNull @Valid Boolean expectedCompleted,
            @JsonProperty(value="expectedItemRevision",required=true) @Min(0L) @Valid Long expectedItemRevision,
            @JsonProperty(value="baseRevision",required=true) @NotNull @Min(1L) @Valid Long baseRevision,
            @JsonProperty(value="clientMutationId",required=true) @NotNull @Valid UUID clientMutationId
    ) {}
    public record TaskSegment(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="taskId",required=true) @NotNull @Valid UUID taskId,
            @JsonProperty(value="scheduledOn",required=true) @Valid LocalDate scheduledOn,
            @JsonProperty(value="minutes",required=true) @NotNull @Min(1L) @Valid Integer minutes,
            @JsonProperty(value="state",required=true) @NotNull @Pattern(regexp="^(?:SCHEDULED|UNSCHEDULED|AWAITING_DATE)$") @Valid String state,
            @JsonProperty(value="sortOrder",required=true) @NotNull @Min(0L) @Valid Integer sortOrder
    ) {}
    public record TaskTemplate(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="kind",required=true) @NotNull @Pattern(regexp="^(?:PAPER|REVIEW)$") @Valid String kind,
            @JsonProperty(value="title",required=true) @NotNull @Size(min=1,max=500) @Valid String title,
            @JsonProperty(value="estimatedMinutes",required=true) @NotNull @Min(1L) @Valid Integer estimatedMinutes,
            @JsonProperty(value="resource",required=true) @Valid Resource resource,
            @JsonProperty(value="sortOrder",required=true) @NotNull @Min(0L) @Valid Integer sortOrder
    ) {}
    public record TemplateDraft(
            @JsonProperty(value="templates",required=true) @NotNull @Size(min=0) @Valid List<@NotNull TaskTemplate> templates
    ) {}
    public record Unlock(
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="cycleId",required=true) @NotNull @Valid UUID cycleId,
            @JsonProperty(value="canDownloadPapers",required=true) @NotNull @Valid Boolean canDownloadPapers,
            @JsonProperty(value="canWriteScores",required=true) @NotNull @Valid Boolean canWriteScores,
            @JsonProperty(value="canApplyMock",required=true) @NotNull @Valid Boolean canApplyMock,
            @JsonProperty(value="missingChapterIds",required=true) @NotNull @Size(min=0) @Valid List<@NotNull UUID> missingChapterIds,
            @JsonProperty(value="sources",required=true) @NotNull @Size(min=0) @Valid List<@NotNull String> sources,
            @JsonProperty(value="activeOverride",required=true) @Valid UnlockOverride activeOverride,
            @JsonProperty(value="skipWindow",required=true) @NotNull @Valid UnlockSkipWindow skipWindow,
            @JsonProperty(value="evaluatedAt",required=true) @NotNull @Valid Instant evaluatedAt
    ) {}
    public record UnlockOverride(
            @JsonProperty(value="id",required=true) @NotNull @Valid UUID id,
            @JsonProperty(value="courseId",required=true) @NotNull @Valid UUID courseId,
            @JsonProperty(value="cycleId",required=true) @NotNull @Valid UUID cycleId,
            @JsonProperty(value="confirmedAt",required=true) @NotNull @Valid Instant confirmedAt,
            @JsonProperty(value="examDateSnapshot",required=true) @NotNull @Valid LocalDate examDateSnapshot,
            @JsonProperty(value="revokedAt",required=true) @Valid Instant revokedAt,
            @JsonProperty(value="revision",required=true) @NotNull @Min(0L) @Valid Long revision
    ) {}
    public record UnlockSkipWindow(
            @JsonProperty(value="examDate",required=true) @Valid LocalDate examDate,
            @JsonProperty(value="windowStart",required=true) @Valid LocalDate windowStart,
            @JsonProperty(value="windowEnd",required=true) @Valid LocalDate windowEnd,
            @JsonProperty(value="canConfirm",required=true) @NotNull @Valid Boolean canConfirm,
            @JsonProperty(value="reason",required=true) @Valid String reason
    ) {}
}
