"""Generate closed Java records from the checked-in contract, without network/codegen dependencies."""
from pathlib import Path
import json,re,sys
root=Path(__file__).resolve().parents[1]
schemas=json.loads((root/'src/main/resources/business-contract-schemas.json').read_text())
roots='PlanConfig PlanCreate Plan PlanSummary PlanPreview PreviewConfirm RescheduleRequest TaskCompletionWrite TaskCompletion Dashboard CourseAdminWrite CycleWrite ReleaseCreate ContentRelease CatalogDraft KnowledgeDraft QuestionBankDraft TemplateDraft AssessmentPolicyWrite AssessmentPolicy ReleaseValidation PaperWrite InvalidatePass PassInvalidationResult BankAlert AuditEvent LegacyReviewDecision LegacyPassReview LegacyPracticeCreditDecision LegacyPracticeCreditResult LegacyDetail LegacyRecordSummary'.split()
records={}
def merge(s):
 if '$ref' in s:return merge(schemas[s['$ref'].split('/')[-1]])
 if 'allOf' in s:
  out={'type':'object','properties':{},'required':[]}
  for part in s['allOf']:
   m=merge(part);out['properties'].update(m.get('properties',{}));out['required']+=m.get('required',[])
  out.update({k:v for k,v in s.items() if k!='allOf'})
  return out
 return s

def typ(s,name):
 if '$ref' in s:
  ref=s['$ref'].split('/')[-1];record(ref,schemas[ref]);return ref
 if 'allOf' in s:s=merge(s)
 if 'anyOf' in s or 'oneOf' in s:
  parts=s.get('anyOf',s.get('oneOf'))
  nonnull=[p for p in parts if p.get('enum')!=[None]]
  if len(nonnull)==1:return typ(nonnull[0],name)
  # Heterogeneous historical JSON or resource tagged union stays explicitly opaque.
  return 'JsonNode'
 t=s.get('type')
 if t=='object':
  if not s.get('properties'):return 'JsonNode'
  record(name,s);return name
 if t=='array':
  item=merge(s['items']); nonnull='' if item.get('nullable') else '@NotNull '
  return 'List<'+nonnull+typ(s['items'],name+'Item')+'>'
 if t=='string':return {'date':'LocalDate','date-time':'Instant','uuid':'UUID'}.get(s.get('format'),'String')
 if t=='boolean':return 'Boolean'
 if t=='integer':return 'Long' if s.get('format')=='int64' or name.endswith('Revision') else 'Integer'
 if t=='number':return 'BigDecimal'
 return 'JsonNode'

def annotation(s,required):
 out=[]
 if not required:out.append('@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)')
 if required:out.append('@JsonProperty(value='+json.dumps(current_field)+',required=true)')
 if required and not s.get('nullable') and not any(p.get('enum')==[None] for p in s.get('anyOf',[])):out.append('@NotNull')
 t=s.get('type')
 if t in ['array','string'] and any(k in s for k in ['minItems','maxItems','minLength','maxLength']):
  bounds=[]
  for src,dst in [('minItems','min'),('maxItems','max'),('minLength','min'),('maxLength','max')]:
   if src in s:bounds.append(dst+'='+str(s[src]))
  out.append('@Size('+','.join(bounds)+')')
 if t=='integer':
  for src,dst in [('minimum','Min'),('maximum','Max')]:
   if src in s:out.append('@'+dst+'('+str(s[src])+'L)')
 if t=='number':
  for src,dst in [('minimum','DecimalMin'),('maximum','DecimalMax')]:
   if src in s:out.append('@'+dst+'("'+str(s[src])+'")')
 if t=='string':
  pattern=s.get('pattern')
  if s.get('enum'):pattern='^(?:'+'|'.join(re.escape(str(v)) for v in s['enum'])+')$'
  if pattern:out.append('@Pattern(regexp='+json.dumps(pattern)+')')
 if t=='boolean' and s.get('enum')==[True]:out.append('@AssertTrue')
 out.append('@Valid')
 return ' '.join(out)+' '

def record(name,s):
 global current_field
 if name in records:return
 records[name]=''
 s=merge(s);props=s.get('properties',{});req=s.get('required',[]);fields=[]
 for key,value in props.items():
  ft=typ(value,name+key[0].upper()+key[1:]);current_field=key
  fields.append('            '+annotation(value,key in req)+ft+' '+key)
 records[name]='    public record '+name+'(\n'+',\n'.join(fields)+'\n    ) {}\n'
for name in roots:record(name,schemas[name])
result='''package cn.xuexizhitu.contract;

// Generated by scripts/generate-workflow-dtos.py; run with --check in verification.
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.*;
import java.math.BigDecimal;
import java.util.*;

public final class WorkflowDtos {
    private WorkflowDtos() {}
'''+''.join(records[k] for k in sorted(records))+'}\n'
p=root/'src/main/java/cn/xuexizhitu/contract/WorkflowDtos.java'
if '--check' in sys.argv:
 if not p.exists() or p.read_text()!=result:raise SystemExit('Workflow DTOs are stale')
else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(result)
print('Workflow records:',len(records))
